//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSoruSecenek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnketSoruSecenek()
        {
            this.AnketCevaplaris = new HashSet<AnketCevaplari>();
        }
    
        public int AnketSoruSecenekID { get; set; }
        public int AnketSoruID { get; set; }
        public int SiraNo { get; set; }
        public string SecenekAdi { get; set; }
        public bool IsYaziOrSayi { get; set; }
        public bool IsEkAciklamaGir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplari> AnketCevaplaris { get; set; }
        public virtual AnketSoru AnketSoru { get; set; }
    }
}
