//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecBelgeTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasvuruSurecBelgeTipleri()
        {
            this.BasvuruSurecBelgeTipleriYuklemeSeklis = new HashSet<BasvuruSurecBelgeTipleriYuklemeSekli>();
        }
    
        public int BasvuruSurecBelgeTipID { get; set; }
        public int BasvuruSurecID { get; set; }
        public int BasvuruBelgeTipID { get; set; }
        public bool IsZorunlu { get; set; }
        public Nullable<bool> IsYerliOrYabanci { get; set; }
    
        public virtual BasvuruBelgeTipleri BasvuruBelgeTipleri { get; set; }
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecBelgeTipleriYuklemeSekli> BasvuruSurecBelgeTipleriYuklemeSeklis { get; set; }
    }
}
