//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecMulakatSinavTurleri
    {
        public int BasvuruSurecMulakatSinavTurID { get; set; }
        public int BasvuruSurecID { get; set; }
        public int MulakatSinavTurID { get; set; }
        public Nullable<int> YuzdeOran { get; set; }
        public bool Zorunlu { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual MulakatSinavTurleri MulakatSinavTurleri { get; set; }
    }
}
