//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlar
    {
        public int BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlarID { get; set; }
        public int BasvuruSurecSinavTipleriOTNotAralikID { get; set; }
        public string ProgramKod { get; set; }
    
        public virtual BasvuruSurecSinavTipleriOTNotAraliklari BasvuruSurecSinavTipleriOTNotAraliklari { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
