//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecBelgeTipleriYuklemeSekli
    {
        public int BasvuruSurecBelgeTipleriYuklemeSekliID { get; set; }
        public int BasvuruSurecBelgeTipID { get; set; }
        public int BasvuruBelgeTipID { get; set; }
        public int SinavTipKod { get; set; }
        public bool IsKayitSonrasiGetirilecek { get; set; }
    
        public virtual BasvuruBelgeTipleri BasvuruBelgeTipleri { get; set; }
        public virtual BasvuruSurecBelgeTipleri BasvuruSurecBelgeTipleri { get; set; }
    }
}
