//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecKotalar
    {
        public int BasvuruSurecKotaID { get; set; }
        public int BasvuruSurecID { get; set; }
        public int OgrenimTipKod { get; set; }
        public int KotaID { get; set; }
        public string ProgramKod { get; set; }
        public bool OrtakKota { get; set; }
        public Nullable<int> OrtakKotaSayisi { get; set; }
        public int AlanIciKota { get; set; }
        public int AlanDisiKota { get; set; }
        public Nullable<int> AlanIciEkKota { get; set; }
        public Nullable<int> AlanDisiEkKota { get; set; }
        public Nullable<double> MinAles { get; set; }
        public Nullable<double> MinAGNO { get; set; }
        public bool YokOgrenciKontroluYap { get; set; }
        public bool IsAlandisiBolumKisitlamasi { get; set; }
        public Nullable<bool> MulakatSurecineGirecek { get; set; }
        public Nullable<bool> IsAlesYerineDosyaNotuIstensin { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
