//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecSinavNotlari
    {
        public int BasvuruSurecSinavNotlariID { get; set; }
        public int BasvuruSurecSinavTipID { get; set; }
        public string SinavNotAdi { get; set; }
        public double SinavNotDeger { get; set; }
    
        public virtual BasvuruSurecSinavTipleri BasvuruSurecSinavTipleri { get; set; }
    }
}
