//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvurularSinavBilgi
    {
        public int BasvuruSinavBilgiID { get; set; }
        public int BasvuruID { get; set; }
        public int SinavTipID { get; set; }
        public Nullable<int> SinavTipKod { get; set; }
        public int SinavTipGrupID { get; set; }
        public Nullable<bool> IsTaahhutVar { get; set; }
        public Nullable<int> WsSinavYil { get; set; }
        public string WsSinavDonem { get; set; }
        public Nullable<int> WsSonucID { get; set; }
        public Nullable<System.DateTime> WsAciklanmaTarihi { get; set; }
        public string WsSinavDili { get; set; }
        public string WsXmlData { get; set; }
        public Nullable<System.DateTime> SinavTarihi { get; set; }
        public Nullable<int> SinavDilID { get; set; }
        public Nullable<int> SubSinavAralikID { get; set; }
        public Nullable<double> BasvuruSurecSubNot { get; set; }
        public double SinavNotu { get; set; }
    
        public virtual Basvurular Basvurular { get; set; }
        public virtual SinavDilleri SinavDilleri { get; set; }
        public virtual SinavTipGruplari SinavTipGruplari { get; set; }
        public virtual SinavTipleri SinavTipleri { get; set; }
    }
}
