//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecProgramlarAlandisiBolumKisitlamalari
    {
        public int BasvuruSurecProgramlarAlandisiBolumKisitlamaID { get; set; }
        public int BasvuruSurecID { get; set; }
        public string ProgramKod { get; set; }
        public int OgrenciBolumID { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual OgrenciBolumleri OgrenciBolumleri { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
