//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvurular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basvurular()
        {
            this.AnketCevaplaris = new HashSet<AnketCevaplari>();
            this.BasvurularSinavBilgis = new HashSet<BasvurularSinavBilgi>();
            this.BasvurularTercihleris = new HashSet<BasvurularTercihleri>();
            this.BasvurularYuklenenBelgelers = new HashSet<BasvurularYuklenenBelgeler>();
            this.GonderilenMaillers = new HashSet<GonderilenMailler>();
            this.MulakatSonuclaris = new HashSet<MulakatSonuclari>();
        }
    
        public int BasvuruID { get; set; }
        public System.Guid RowID { get; set; }
        public int BasvuruSurecID { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int BasvuruDurumID { get; set; }
        public string BasvuruDurumAciklamasi { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> KullaniciTipID { get; set; }
        public string ResimAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> MedeniHalID { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        public string KizlikSoyadi { get; set; }
        public string AnaAdi { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<int> DogumYeriKod { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> NufusilIlceKod { get; set; }
        public Nullable<int> CiltNo { get; set; }
        public Nullable<int> AileNo { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string TcKimlikNo { get; set; }
        public Nullable<int> UyrukKod { get; set; }
        public Nullable<int> SehirKod { get; set; }
        public string IsTel { get; set; }
        public string EvTel { get; set; }
        public string CepTel { get; set; }
        public string EMail { get; set; }
        public string Adres { get; set; }
        public string Adres2 { get; set; }
        public Nullable<int> LUniversiteID { get; set; }
        public string LFakulteAdi { get; set; }
        public Nullable<int> LOgrenciBolumID { get; set; }
        public Nullable<int> LOgrenimDurumID { get; set; }
        public Nullable<System.DateTime> LBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> LMezuniyetTarihi { get; set; }
        public Nullable<int> LNotSistemID { get; set; }
        public Nullable<double> LMezuniyetNotu { get; set; }
        public Nullable<double> LMezuniyetNotu100LukSistem { get; set; }
        public Nullable<bool> LEgitimDiliTurkce { get; set; }
        public Nullable<int> YLUniversiteID { get; set; }
        public string YLFakulteAdi { get; set; }
        public Nullable<int> YLOgrenciBolumID { get; set; }
        public Nullable<System.DateTime> YLBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> YLMezuniyetTarihi { get; set; }
        public Nullable<int> YLNotSistemID { get; set; }
        public Nullable<double> YLMezuniyetNotu { get; set; }
        public Nullable<double> YLMezuniyetNotu100LukSistem { get; set; }
        public Nullable<bool> YLEgitimDiliTurkce { get; set; }
        public Nullable<int> DRUniversiteID { get; set; }
        public string DRFakulteAdi { get; set; }
        public Nullable<int> DROgrenciBolumID { get; set; }
        public Nullable<System.DateTime> DRBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> DRMezuniyetTarihi { get; set; }
        public Nullable<int> DRNotSistemID { get; set; }
        public Nullable<double> DRMezuniyetNotu { get; set; }
        public Nullable<double> DRMezuniyetNotu100LukSistem { get; set; }
        public Nullable<bool> DREgitimDiliTurkce { get; set; }
        public Nullable<bool> Kapatildi { get; set; }
        public string KapatmaAciklamasi { get; set; }
        public Nullable<bool> YokOgrenimKaydiVar { get; set; }
        public Nullable<System.DateTime> YokOgrenimKontrolTarihi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplari> AnketCevaplaris { get; set; }
        public virtual BasvuruDurumlari BasvuruDurumlari { get; set; }
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual KullaniciTipleri KullaniciTipleri { get; set; }
        public virtual MedeniHaller MedeniHaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularSinavBilgi> BasvurularSinavBilgis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularTercihleri> BasvurularTercihleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularYuklenenBelgeler> BasvurularYuklenenBelgelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailler> GonderilenMaillers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatSonuclari> MulakatSonuclaris { get; set; }
    }
}
