//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecSinavTipleriOT_SNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasvuruSurecSinavTipleriOT_SNA()
        {
            this.BasvuruSurecSinavTipleriOT_SNA_OT = new HashSet<BasvuruSurecSinavTipleriOT_SNA_OT>();
            this.BasvuruSurecSinavTipleriOT_SNA_PR = new HashSet<BasvuruSurecSinavTipleriOT_SNA_PR>();
        }
    
        public int BasvuruSurecSinavTipleriOT_SNAID { get; set; }
        public int BasvuruSurecID { get; set; }
        public int SinavTipID { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOT_SNA_OT> BasvuruSurecSinavTipleriOT_SNA_OT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOT_SNA_PR> BasvuruSurecSinavTipleriOT_SNA_PR { get; set; }
        public virtual SinavTipleri SinavTipleri { get; set; }
    }
}
