//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvurularTercihleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasvurularTercihleri()
        {
            this.BasvurularTercihleriKayitOdemeleris = new HashSet<BasvurularTercihleriKayitOdemeleri>();
            this.MulakatSonuclaris = new HashSet<MulakatSonuclari>();
        }
    
        public int BasvuruTercihID { get; set; }
        public int BasvuruID { get; set; }
        public int SiraNo { get; set; }
        public int OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public int AlanTipID { get; set; }
        public System.Guid UniqueID { get; set; }
        public Nullable<int> KayitSiraNo { get; set; }
        public Nullable<bool> IsSecilenTercih { get; set; }
        public Nullable<bool> IsOncedenMezuniyetiVar { get; set; }
        public string MezuniyetBelgesiYolu { get; set; }
        public string MezuniyetBelgesiAdi { get; set; }
        public Nullable<bool> IsOgrenimUcretiOrKatkiPayi { get; set; }
        public Nullable<double> ProgramUcret { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual AlanTipleri AlanTipleri { get; set; }
        public virtual Basvurular Basvurular { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Programlar Programlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularTercihleriKayitOdemeleri> BasvurularTercihleriKayitOdemeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatSonuclari> MulakatSonuclaris { get; set; }
    }
}
