//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BelgeTipDetaySaatler
    {
        public int BelgeTipDetaySaatlerID { get; set; }
        public int BelgeTipDetayID { get; set; }
        public int HaftaGunID { get; set; }
        public System.TimeSpan TalepBaslangicSaat { get; set; }
        public System.TimeSpan TalepBitisSaat { get; set; }
        public int EklenecekGun { get; set; }
        public System.TimeSpan TeslimBaslangicSaat { get; set; }
        public System.TimeSpan TeslimBitisSaat { get; set; }
    
        public virtual BelgeTipDetay BelgeTipDetay { get; set; }
        public virtual HaftaGunleri HaftaGunleri { get; set; }
    }
}
