//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BelgeTipDetayBelgeler
    {
        public int BelgeTipDetayBelgelerID { get; set; }
        public int BelgeTipDetayID { get; set; }
        public int BelgeTipID { get; set; }
    
        public virtual BelgeTipDetay BelgeTipDetay { get; set; }
        public virtual BelgeTipleri BelgeTipleri { get; set; }
    }
}
