//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolumEslestir
    {
        public int BolumEslestirID { get; set; }
        public string ProgramKod { get; set; }
        public int OgrenciBolumID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OgrenciBolumleri OgrenciBolumleri { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
