//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_vW_BasvuruKayitSinavBilgi
    {
        public Nullable<int> YIL { get; set; }
        public int DonemID { get; set; }
        public string DonemAdi { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string EMail { get; set; }
        public int OgrenimTipKod { get; set; }
        public string OgrenimTipAdi { get; set; }
        public string AnabilimDaliAdi { get; set; }
        public string ProgramAdi { get; set; }
        public Nullable<double> LMezuniyetNotu100LukSistem { get; set; }
        public Nullable<double> YLMezuniyetNotu100LukSistem { get; set; }
        public string SinavAdi { get; set; }
        public Nullable<double> SinavNotu { get; set; }
    }
}
