//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_vW_BasvuruAlesOrtalamalar
    {
        public string EnstituKisaAd { get; set; }
        public int BaslangicYil { get; set; }
        public string DonemAdi { get; set; }
        public Nullable<double> OnaylananBasvurularAlesOrtalama { get; set; }
        public Nullable<double> KayitOlanOgrenciAlesOrtalama { get; set; }
        public Nullable<double> OnaylananBasvurularLisansAgnoOrtalama { get; set; }
        public Nullable<double> KayitOlanOgrenciLisansAgnoOrtalama { get; set; }
    }
}
