//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonemProjesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonemProjesi()
        {
            this.DonemProjesiBasvurus = new HashSet<DonemProjesiBasvuru>();
        }
    
        public int DonemProjesiID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string EnstituKod { get; set; }
        public bool IsYeniBasvuruYapilabilir { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string OgrenciNo { get; set; }
        public int OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public Nullable<int> KayitOgretimYiliBaslangic { get; set; }
        public Nullable<int> KayitOgretimYiliDonemID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> TezDanismanID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual DonemProjesi DonemProjesi1 { get; set; }
        public virtual DonemProjesi DonemProjesi2 { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemProjesiBasvuru> DonemProjesiBasvurus { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
