//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonemProjesiJurileri
    {
        public int DonemProjesiJuriID { get; set; }
        public int DonemProjesiBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public int RowNum { get; set; }
        public bool IsTezDanismani { get; set; }
        public string UnvanAdi { get; set; }
        public string AdSoyad { get; set; }
        public string EMail { get; set; }
        public string AnabilimdaliAdi { get; set; }
        public Nullable<bool> IsLinkGonderildi { get; set; }
        public Nullable<System.DateTime> LinkGonderimTarihi { get; set; }
        public Nullable<int> LinkGonderenID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> DonemProjesiJuriOnayDurumID { get; set; }
        public Nullable<int> DegerlendirmeYapanID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeIslemTarihi { get; set; }
        public string DegerlendirmeIslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual DonemProjesiBasvuru DonemProjesiBasvuru { get; set; }
        public virtual DonemProjesiJuriOnayDurumlari DonemProjesiJuriOnayDurumlari { get; set; }
    }
}
