//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonemProjesiBasvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonemProjesiBasvuru()
        {
            this.DonemProjesiJurileris = new HashSet<DonemProjesiJurileri>();
            this.SRTalepleris = new HashSet<SRTalepleri>();
        }
    
        public int DonemProjesiBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string FormKodu { get; set; }
        public int DonemProjesiID { get; set; }
        public int DonemProjesiDurumID { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int BasvuruYil { get; set; }
        public int BasvuruDonemID { get; set; }
        public int OkuduguDonemNo { get; set; }
        public string ProjeBasligi { get; set; }
        public string ProjeOzeti { get; set; }
        public bool IsOgrenciTaahhut { get; set; }
        public Nullable<int> DonemProjesiEnstituOnayDurumID { get; set; }
        public System.DateTime EnstituOnayTarihi { get; set; }
        public string EnstituOnayAciklama { get; set; }
        public int TezDanismanID { get; set; }
        public Nullable<bool> IsDanismanOnay { get; set; }
        public Nullable<System.DateTime> DanismanOnayTarihi { get; set; }
        public string DanismanOnayAciklama { get; set; }
        public Nullable<int> ToplamKaynakOrani { get; set; }
        public Nullable<int> TekKaynakOrani { get; set; }
        public string IntihalRaporuDosyaAdi { get; set; }
        public string IntihalRaporuDosyaYolu { get; set; }
        public Nullable<bool> IsDanismanDegerlendirmeHatirlatmasiYapildi { get; set; }
        public Nullable<System.DateTime> DanismanDegerlendirmeHatirlatmasiTarihi { get; set; }
        public Nullable<bool> IsOyBirligiOrCoklugu { get; set; }
        public Nullable<int> DonemProjesiJuriOnayDurumID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeSonucMailTarihi { get; set; }
        public Nullable<bool> EYKYaGonderildi { get; set; }
        public Nullable<int> EYKYaGonderildiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaGonderildiIslemTarihi { get; set; }
        public string EYKYaGonderimDurumAciklamasi { get; set; }
        public Nullable<bool> EYKYaHazirlandi { get; set; }
        public Nullable<int> EYKYaHazirlandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaHazirlandiIslemTarihi { get; set; }
        public Nullable<bool> EYKDaOnaylandi { get; set; }
        public Nullable<int> EYKDaOnaylandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKTarihi { get; set; }
        public Nullable<System.DateTime> EYKDaOnaylandiIslemTarihi { get; set; }
        public string EYKDaOnaylanmadiDurumAciklamasi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual DonemProjesi DonemProjesi { get; set; }
        public virtual DonemProjesiDurumlari DonemProjesiDurumlari { get; set; }
        public virtual DonemProjesiEnstituOnayDurumlari DonemProjesiEnstituOnayDurumlari { get; set; }
        public virtual DonemProjesiJuriOnayDurumlari DonemProjesiJuriOnayDurumlari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemProjesiJurileri> DonemProjesiJurileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepleri> SRTalepleris { get; set; }
    }
}
