//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonemProjesiEnstituOnayDurumlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonemProjesiEnstituOnayDurumlari()
        {
            this.DonemProjesiBasvurus = new HashSet<DonemProjesiBasvuru>();
        }
    
        public int DonemProjesiEnstituOnayDurumID { get; set; }
        public bool IsTekrarBasvuruYapabilir { get; set; }
        public string EnstituOnayDurumAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemProjesiBasvuru> DonemProjesiBasvurus { get; set; }
    }
}
