//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donemler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donemler()
        {
            this.BasvuruSurecs = new HashSet<BasvuruSurec>();
            this.BelgeTalepleris = new HashSet<BelgeTalepleri>();
            this.DonemProjesiBasvurus = new HashSet<DonemProjesiBasvuru>();
            this.KayitSilmeBasvurus = new HashSet<KayitSilmeBasvuru>();
            this.MezuniyetBasvurularis = new HashSet<MezuniyetBasvurulari>();
            this.MezuniyetSurecis = new HashSet<MezuniyetSureci>();
            this.MezuniyetYonetmelikleris = new HashSet<MezuniyetYonetmelikleri>();
            this.MezuniyetYonetmelikleris1 = new HashSet<MezuniyetYonetmelikleri>();
            this.TDOBasvurus = new HashSet<TDOBasvuru>();
            this.TDOBasvuruDanismen = new HashSet<TDOBasvuruDanisman>();
            this.TIBasvurus = new HashSet<TIBasvuru>();
            this.TIBasvuruAraRapors = new HashSet<TIBasvuruAraRapor>();
            this.TijBasvurus = new HashSet<TijBasvuru>();
            this.TijBasvuruOneris = new HashSet<TijBasvuruOneri>();
            this.ToBasvurus = new HashSet<ToBasvuru>();
            this.ToBasvuruSavunmas = new HashSet<ToBasvuruSavunma>();
            this.YeterlikBasvurus = new HashSet<YeterlikBasvuru>();
            this.YeterlikSurecis = new HashSet<YeterlikSureci>();
        }
    
        public int DonemID { get; set; }
        public string DonemAdi { get; set; }
        public string DonemAralikAyGun { get; set; }
        public bool IsWsDonem { get; set; }
        public string WsDonemKod { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurec> BasvuruSurecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTalepleri> BelgeTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemProjesiBasvuru> DonemProjesiBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KayitSilmeBasvuru> KayitSilmeBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulari> MezuniyetBasvurularis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureci> MezuniyetSurecis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYonetmelikleri> MezuniyetYonetmelikleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYonetmelikleri> MezuniyetYonetmelikleris1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuru> TDOBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuruDanisman> TDOBasvuruDanismen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuru> TIBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuruAraRapor> TIBasvuruAraRapors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TijBasvuru> TijBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TijBasvuruOneri> TijBasvuruOneris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuru> ToBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunma> ToBasvuruSavunmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikBasvuru> YeterlikBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikSureci> YeterlikSurecis { get; set; }
    }
}
