//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuyuruPopuplar
    {
        public int DuyuruPopupID { get; set; }
        public int DuyuruID { get; set; }
        public int DuyuruPopupTipID { get; set; }
    
        public virtual Duyurular Duyurular { get; set; }
        public virtual DuyuruPopupTipleri DuyuruPopupTipleri { get; set; }
    }
}
