//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enstituler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enstituler()
        {
            this.Ankets = new HashSet<Anket>();
            this.BasvuruSurecs = new HashSet<BasvuruSurec>();
            this.BasvuruSurecSinavTipleris = new HashSet<BasvuruSurecSinavTipleri>();
            this.BelgeTalepleris = new HashSet<BelgeTalepleri>();
            this.BelgeTipDetays = new HashSet<BelgeTipDetay>();
            this.DonemProjesis = new HashSet<DonemProjesi>();
            this.DonemProjesiMuafOgrencilers = new HashSet<DonemProjesiMuafOgrenciler>();
            this.Duyurulars = new HashSet<Duyurular>();
            this.GonderilenMaillers = new HashSet<GonderilenMailler>();
            this.KullaniciEnstituYetkileris = new HashSet<KullaniciEnstituYetkileri>();
            this.MailSablonlaris = new HashSet<MailSablonlari>();
            this.MesajKategorileris = new HashSet<MesajKategorileri>();
            this.Mesajlars = new HashSet<Mesajlar>();
            this.MezuniyetSurecis = new HashSet<MezuniyetSureci>();
            this.MezuniyetSureciYonetmelikleris = new HashSet<MezuniyetSureciYonetmelikleri>();
            this.MezuniyetYonetmelikleris = new HashSet<MezuniyetYonetmelikleri>();
            this.OgrenimTipleris = new HashSet<OgrenimTipleri>();
            this.SinavTipleris = new HashSet<SinavTipleri>();
            this.SinavTipleriOTNotAraliklaris = new HashSet<SinavTipleriOTNotAraliklari>();
            this.SRSalonlars = new HashSet<SRSalonlar>();
            this.SRTalepleris = new HashSet<SRTalepleri>();
            this.TalepSurecleris = new HashSet<TalepSurecleri>();
            this.TDOBasvurus = new HashSet<TDOBasvuru>();
            this.TIBasvurus = new HashSet<TIBasvuru>();
            this.TijBasvurus = new HashSet<TijBasvuru>();
            this.ToBasvurus = new HashSet<ToBasvuru>();
            this.YeterlikSurecis = new HashSet<YeterlikSureci>();
        }
    
        public string EnstituKod { get; set; }
        public string EnstituAd { get; set; }
        public string EnstituKisaAd { get; set; }
        public string EnstituLUiletisimMailAdresi { get; set; }
        public string SmtpHost { get; set; }
        public string SmtpKullaniciAdi { get; set; }
        public string SmtpMailAdresi { get; set; }
        public string SmtpPortAdresi { get; set; }
        public bool SmtpSSL { get; set; }
        public string SmtpSifre { get; set; }
        public string SistemErisimAdresi { get; set; }
        public string WebAdresi { get; set; }
        public int ToplamKayitKota { get; set; }
        public string TestEmailAddress { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anket> Ankets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurec> BasvuruSurecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleri> BasvuruSurecSinavTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTalepleri> BelgeTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTipDetay> BelgeTipDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemProjesi> DonemProjesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonemProjesiMuafOgrenciler> DonemProjesiMuafOgrencilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyurular> Duyurulars { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailler> GonderilenMaillers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciEnstituYetkileri> KullaniciEnstituYetkileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailSablonlari> MailSablonlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajKategorileri> MesajKategorileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureci> MezuniyetSurecis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureciYonetmelikleri> MezuniyetSureciYonetmelikleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYonetmelikleri> MezuniyetYonetmelikleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenimTipleri> OgrenimTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleri> SinavTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleriOTNotAraliklari> SinavTipleriOTNotAraliklaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRSalonlar> SRSalonlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepleri> SRTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepSurecleri> TalepSurecleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuru> TDOBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuru> TIBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TijBasvuru> TijBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuru> ToBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikSureci> YeterlikSurecis { get; set; }
    }
}
