//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitSilmeBasvuru
    {
        public int KayitSilmeBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string EnstituKod { get; set; }
        public int KayitSilmeDurumID { get; set; }
        public int OgretimYiliBaslangic { get; set; }
        public int DonemID { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string OgrenciNo { get; set; }
        public int OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public Nullable<int> KayitOgretimYiliBaslangic { get; set; }
        public Nullable<int> KayitOgretimYiliDonemID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public System.DateTime YeterlikSozluSinavTarihi { get; set; }
        public string NufusKayitOrnekDosyaAdi { get; set; }
        public string NufusKayitOrnekDosyaYolu { get; set; }
        public bool IsTaahhutOnay { get; set; }
        public Nullable<bool> IsHarcBirimiOnayladi { get; set; }
        public Nullable<int> HarcBirimiOnayYapanID { get; set; }
        public Nullable<System.DateTime> HarcBirimiOnayIslemTarihi { get; set; }
        public string HarcBirimiOnayAciklamasi { get; set; }
        public Nullable<bool> IsKutuphaneBirimiOnayladi { get; set; }
        public Nullable<int> KutuphaneBirimiOnayYapanID { get; set; }
        public Nullable<System.DateTime> KutuphaneBirimiOnayIslemTarihi { get; set; }
        public string KutuphaneBirimiOnayAciklamasi { get; set; }
        public Nullable<bool> EYKYaGonderildi { get; set; }
        public Nullable<int> EYKYaGonderildiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaGonderildiIslemTarihi { get; set; }
        public string EYKYaGonderimDurumAciklamasi { get; set; }
        public Nullable<bool> EYKYaHazirlandi { get; set; }
        public Nullable<int> EYKYaHazirlandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaHazirlandiIslemTarihi { get; set; }
        public Nullable<System.DateTime> EYKTarihi { get; set; }
        public string EYKSayisi { get; set; }
        public Nullable<bool> EYKDaOnaylandi { get; set; }
        public Nullable<int> EYKDaOnaylandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKDaOnaylandiOnayTarihi { get; set; }
        public string EYKDaOnaylanmadiDurumAciklamasi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual KayitSilmeDurumlari KayitSilmeDurumlari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
