//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciOgrenimleri
    {
        public int KullaniciOgrenimID { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> OgrenimDurumID { get; set; }
        public Nullable<int> OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public string OgrenciNo { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> KayitYilBaslangic { get; set; }
        public Nullable<int> KayitDonemID { get; set; }
        public Nullable<int> DanismanID { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
