//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.AlesTipleris = new HashSet<AlesTipleri>();
            this.AnabilimDaliYeterlikKomiteUyeleris = new HashSet<AnabilimDaliYeterlikKomiteUyeleri>();
            this.AnabilimDallaris = new HashSet<AnabilimDallari>();
            this.Ankets = new HashSet<Anket>();
            this.Ayarlars = new HashSet<Ayarlar>();
            this.BasvuruBelgeTipleris = new HashSet<BasvuruBelgeTipleri>();
            this.BasvuruDurumlaris = new HashSet<BasvuruDurumlari>();
            this.Basvurulars = new HashSet<Basvurular>();
            this.BasvurularTercihleris = new HashSet<BasvurularTercihleri>();
            this.BasvurularTercihleriKayitOdemeleris = new HashSet<BasvurularTercihleriKayitOdemeleri>();
            this.BasvuruSurecs = new HashSet<BasvuruSurec>();
            this.BasvuruSurecOgrenimTipleris = new HashSet<BasvuruSurecOgrenimTipleri>();
            this.BasvuruSurecSinavTipleris = new HashSet<BasvuruSurecSinavTipleri>();
            this.BelgeDurumlaris = new HashSet<BelgeDurumlari>();
            this.BelgeTalepleris = new HashSet<BelgeTalepleri>();
            this.BelgeTipDetays = new HashSet<BelgeTipDetay>();
            this.BelgeTipleris = new HashSet<BelgeTipleri>();
            this.Birimlers = new HashSet<Birimler>();
            this.BolumEslestirs = new HashSet<BolumEslestir>();
            this.Duyurulars = new HashSet<Duyurular>();
            this.Enstitulers = new HashSet<Enstituler>();
            this.GonderilenMailKullanicilars = new HashSet<GonderilenMailKullanicilar>();
            this.GonderilenMaillers = new HashSet<GonderilenMailler>();
            this.KullaniciEnstituYetkileris = new HashSet<KullaniciEnstituYetkileri>();
            this.Kullanicilar1 = new HashSet<Kullanicilar>();
            this.KullaniciProgramlaris = new HashSet<KullaniciProgramlari>();
            this.MailSablonlaris = new HashSet<MailSablonlari>();
            this.MesajKategorileris = new HashSet<MesajKategorileri>();
            this.Mesajlars = new HashSet<Mesajlar>();
            this.MezuniyetBasvurularis = new HashSet<MezuniyetBasvurulari>();
            this.MezuniyetSurecis = new HashSet<MezuniyetSureci>();
            this.MezuniyetSureciKriterMuafOgrencilers = new HashSet<MezuniyetSureciKriterMuafOgrenciler>();
            this.MezuniyetYayinTurleris = new HashSet<MezuniyetYayinTurleri>();
            this.MezuniyetYonetmelikleris = new HashSet<MezuniyetYonetmelikleri>();
            this.Mulakats = new HashSet<Mulakat>();
            this.OgrenciBolumleris = new HashSet<OgrenciBolumleri>();
            this.OgrenimTipleris = new HashSet<OgrenimTipleri>();
            this.Programlars = new HashSet<Programlar>();
            this.Sehirlers = new HashSet<Sehirler>();
            this.SinavTipleris = new HashSet<SinavTipleri>();
            this.SistemBilgilendirmes = new HashSet<SistemBilgilendirme>();
            this.SRSalonlars = new HashSet<SRSalonlar>();
            this.SRTalepleris = new HashSet<SRTalepleri>();
            this.TalepGelenTaleplers = new HashSet<TalepGelenTalepler>();
            this.TDOBasvurus = new HashSet<TDOBasvuru>();
            this.TDOBasvuruDanismen = new HashSet<TDOBasvuruDanisman>();
            this.TIBasvurus = new HashSet<TIBasvuru>();
            this.TIBasvuruAraRapors = new HashSet<TIBasvuruAraRapor>();
            this.TijBasvurus = new HashSet<TijBasvuru>();
            this.TijBasvuruOneris = new HashSet<TijBasvuruOneri>();
            this.ToBasvurus = new HashSet<ToBasvuru>();
            this.ToBasvuruSavunmas = new HashSet<ToBasvuruSavunma>();
            this.YeterlikBasvurus = new HashSet<YeterlikBasvuru>();
            this.YeterlikBasvuruKomitelers = new HashSet<YeterlikBasvuruKomiteler>();
            this.YeterlikSureciKriterMuafOgrencilers = new HashSet<YeterlikSureciKriterMuafOgrenciler>();
            this.Rollers = new HashSet<Roller>();
        }
    
        public int KullaniciID { get; set; }
        public System.Guid UserKey { get; set; }
        public int YetkiGrupID { get; set; }
        public string EnstituKod { get; set; }
        public int KullaniciTipID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string SicilNo { get; set; }
        public Nullable<int> UnvanID { get; set; }
        public Nullable<int> BirimID { get; set; }
        public bool ABDKoordinatoru { get; set; }
        public string ResimAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        public string AnaAdi { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<int> DogumYeriKod { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> NufusilIlceKod { get; set; }
        public Nullable<int> CiltNo { get; set; }
        public Nullable<int> AileNo { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string TcKimlikNo { get; set; }
        public Nullable<int> UyrukKod { get; set; }
        public Nullable<int> SehirKod { get; set; }
        public string CepTel { get; set; }
        public string EMail { get; set; }
        public string Adres { get; set; }
        public bool YtuOgrencisi { get; set; }
        public Nullable<int> OgrenimDurumID { get; set; }
        public Nullable<int> OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public string OgrenciNo { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> KayitYilBaslangic { get; set; }
        public Nullable<int> KayitDonemID { get; set; }
        public Nullable<int> DanismanID { get; set; }
        public bool FixedHeader { get; set; }
        public bool FixedSidebar { get; set; }
        public bool ScrollSidebar { get; set; }
        public bool RightSidebar { get; set; }
        public bool CustomNavigation { get; set; }
        public bool ToggledNavigation { get; set; }
        public bool BoxedOrFullWidth { get; set; }
        public string ThemeName { get; set; }
        public string BackgroundImage { get; set; }
        public bool SifresiniDegistirsin { get; set; }
        public bool IsAktif { get; set; }
        public bool IsActiveDirectoryUser { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string Aciklama { get; set; }
        public string ParolaSifirlamaKodu { get; set; }
        public Nullable<System.DateTime> ParolaSifirlamGecerlilikTarihi { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public string LastLogonIP { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlesTipleri> AlesTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnabilimDaliYeterlikKomiteUyeleri> AnabilimDaliYeterlikKomiteUyeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnabilimDallari> AnabilimDallaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anket> Ankets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ayarlar> Ayarlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruBelgeTipleri> BasvuruBelgeTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDurumlari> BasvuruDurumlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularTercihleri> BasvurularTercihleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularTercihleriKayitOdemeleri> BasvurularTercihleriKayitOdemeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurec> BasvuruSurecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecOgrenimTipleri> BasvuruSurecOgrenimTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleri> BasvuruSurecSinavTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeDurumlari> BelgeDurumlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTalepleri> BelgeTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTipDetay> BelgeTipDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTipleri> BelgeTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birimler> Birimlers { get; set; }
        public virtual Birimler Birimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolumEslestir> BolumEslestirs { get; set; }
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyurular> Duyurulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enstituler> Enstitulers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailKullanicilar> GonderilenMailKullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GonderilenMailler> GonderilenMaillers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciEnstituYetkileri> KullaniciEnstituYetkileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilar1 { get; set; }
        public virtual Kullanicilar Kullanicilar2 { get; set; }
        public virtual KullaniciTipleri KullaniciTipleri { get; set; }
        public virtual OgrenimDurumlari OgrenimDurumlari { get; set; }
        public virtual Programlar Programlar { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual Sehirler Sehirler1 { get; set; }
        public virtual Sehirler Sehirler2 { get; set; }
        public virtual Unvanlar Unvanlar { get; set; }
        public virtual Uyruklar Uyruklar { get; set; }
        public virtual YetkiGruplari YetkiGruplari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciProgramlari> KullaniciProgramlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailSablonlari> MailSablonlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesajKategorileri> MesajKategorileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesajlar> Mesajlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulari> MezuniyetBasvurularis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureci> MezuniyetSurecis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureciKriterMuafOgrenciler> MezuniyetSureciKriterMuafOgrencilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYayinTurleri> MezuniyetYayinTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYonetmelikleri> MezuniyetYonetmelikleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mulakat> Mulakats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciBolumleri> OgrenciBolumleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenimTipleri> OgrenimTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programlar> Programlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sehirler> Sehirlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleri> SinavTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SistemBilgilendirme> SistemBilgilendirmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRSalonlar> SRSalonlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepleri> SRTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepGelenTalepler> TalepGelenTaleplers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuru> TDOBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuruDanisman> TDOBasvuruDanismen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuru> TIBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuruAraRapor> TIBasvuruAraRapors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TijBasvuru> TijBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TijBasvuruOneri> TijBasvuruOneris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuru> ToBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunma> ToBasvuruSavunmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikBasvuru> YeterlikBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikBasvuruKomiteler> YeterlikBasvuruKomitelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikSureciKriterMuafOgrenciler> YeterlikSureciKriterMuafOgrencilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roller> Rollers { get; set; }
    }
}
