//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LubsDbEntities : DbContext
    {
        public LubsDbEntities()
            : base("name=LubsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlanTipleri> AlanTipleris { get; set; }
        public virtual DbSet<AlesTipleri> AlesTipleris { get; set; }
        public virtual DbSet<AnabilimDaliYeterlikKomiteUyeleri> AnabilimDaliYeterlikKomiteUyeleris { get; set; }
        public virtual DbSet<AnabilimDallari> AnabilimDallaris { get; set; }
        public virtual DbSet<Anket> Ankets { get; set; }
        public virtual DbSet<AnketCevaplari> AnketCevaplaris { get; set; }
        public virtual DbSet<AnketSoru> AnketSorus { get; set; }
        public virtual DbSet<AnketSoruSecenek> AnketSoruSeceneks { get; set; }
        public virtual DbSet<Ayarlar> Ayarlars { get; set; }
        public virtual DbSet<Aylar> Aylars { get; set; }
        public virtual DbSet<BasvuruAgnoAlimTipleri> BasvuruAgnoAlimTipleris { get; set; }
        public virtual DbSet<BasvuruBelgeTipleri> BasvuruBelgeTipleris { get; set; }
        public virtual DbSet<BasvuruBelgeTipleriYuklemeSekli> BasvuruBelgeTipleriYuklemeSeklis { get; set; }
        public virtual DbSet<BasvuruDurumlari> BasvuruDurumlaris { get; set; }
        public virtual DbSet<Basvurular> Basvurulars { get; set; }
        public virtual DbSet<BasvurularSinavBilgi> BasvurularSinavBilgis { get; set; }
        public virtual DbSet<BasvurularTercihleri> BasvurularTercihleris { get; set; }
        public virtual DbSet<BasvurularTercihleriKayitOdemeleri> BasvurularTercihleriKayitOdemeleris { get; set; }
        public virtual DbSet<BasvurularYuklenenBelgeler> BasvurularYuklenenBelgelers { get; set; }
        public virtual DbSet<BasvuruSurec> BasvuruSurecs { get; set; }
        public virtual DbSet<BasvuruSurecBelgeTipleri> BasvuruSurecBelgeTipleris { get; set; }
        public virtual DbSet<BasvuruSurecBelgeTipleriYuklemeSekli> BasvuruSurecBelgeTipleriYuklemeSeklis { get; set; }
        public virtual DbSet<BasvuruSurecKontrolTipleri> BasvuruSurecKontrolTipleris { get; set; }
        public virtual DbSet<BasvuruSurecKotalar> BasvuruSurecKotalars { get; set; }
        public virtual DbSet<BasvuruSurecMulakatSinavTurleri> BasvuruSurecMulakatSinavTurleris { get; set; }
        public virtual DbSet<BasvuruSurecOgrenimTipleri> BasvuruSurecOgrenimTipleris { get; set; }
        public virtual DbSet<BasvuruSurecOtoMail> BasvuruSurecOtoMails { get; set; }
        public virtual DbSet<BasvuruSurecOTOrtBasvr> BasvuruSurecOTOrtBasvrs { get; set; }
        public virtual DbSet<BasvuruSurecProgramlarAlandisiBolumKisitlamalari> BasvuruSurecProgramlarAlandisiBolumKisitlamalaris { get; set; }
        public virtual DbSet<BasvuruSurecSinavNotlari> BasvuruSurecSinavNotlaris { get; set; }
        public virtual DbSet<BasvuruSurecSinavTarihleri> BasvuruSurecSinavTarihleris { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleri> BasvuruSurecSinavTipleris { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriDil> BasvuruSurecSinavTipleriDils { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriDonem> BasvuruSurecSinavTipleriDonems { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriOT_SNA> BasvuruSurecSinavTipleriOT_SNA { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriOT_SNA_OT> BasvuruSurecSinavTipleriOT_SNA_OT { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriOT_SNA_PR> BasvuruSurecSinavTipleriOT_SNA_PR { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriOTNotAraliklari> BasvuruSurecSinavTipleriOTNotAraliklaris { get; set; }
        public virtual DbSet<BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlar> BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlars { get; set; }
        public virtual DbSet<BasvuruSurecSinavTiplerSubSinavAralik> BasvuruSurecSinavTiplerSubSinavAraliks { get; set; }
        public virtual DbSet<BasvuruSurecTipleri> BasvuruSurecTipleris { get; set; }
        public virtual DbSet<BelgeDurumlari> BelgeDurumlaris { get; set; }
        public virtual DbSet<BelgeTalepAyarlar> BelgeTalepAyarlars { get; set; }
        public virtual DbSet<BelgeTalepleri> BelgeTalepleris { get; set; }
        public virtual DbSet<BelgeTipDetay> BelgeTipDetays { get; set; }
        public virtual DbSet<BelgeTipDetayBelgeler> BelgeTipDetayBelgelers { get; set; }
        public virtual DbSet<BelgeTipDetaySaatler> BelgeTipDetaySaatlers { get; set; }
        public virtual DbSet<BelgeTipleri> BelgeTipleris { get; set; }
        public virtual DbSet<Birimler> Birimlers { get; set; }
        public virtual DbSet<BolumEslestir> BolumEslestirs { get; set; }
        public virtual DbSet<Cinsiyetler> Cinsiyetlers { get; set; }
        public virtual DbSet<Donemler> Donemlers { get; set; }
        public virtual DbSet<DonemProjesi> DonemProjesis { get; set; }
        public virtual DbSet<DonemProjesiAyarlar> DonemProjesiAyarlars { get; set; }
        public virtual DbSet<DonemProjesiBasvuru> DonemProjesiBasvurus { get; set; }
        public virtual DbSet<DonemProjesiDurumlari> DonemProjesiDurumlaris { get; set; }
        public virtual DbSet<DonemProjesiEnstituOnayDurumlari> DonemProjesiEnstituOnayDurumlaris { get; set; }
        public virtual DbSet<DonemProjesiJurileri> DonemProjesiJurileris { get; set; }
        public virtual DbSet<DonemProjesiJuriOnayDurumlari> DonemProjesiJuriOnayDurumlaris { get; set; }
        public virtual DbSet<DonemProjesiMuafOgrenciler> DonemProjesiMuafOgrencilers { get; set; }
        public virtual DbSet<DuyuruEkleri> DuyuruEkleris { get; set; }
        public virtual DbSet<Duyurular> Duyurulars { get; set; }
        public virtual DbSet<DuyuruPopuplar> DuyuruPopuplars { get; set; }
        public virtual DbSet<DuyuruPopupTipleri> DuyuruPopupTipleris { get; set; }
        public virtual DbSet<Enstituler> Enstitulers { get; set; }
        public virtual DbSet<GonderilenMailEkleri> GonderilenMailEkleris { get; set; }
        public virtual DbSet<GonderilenMailKullanicilar> GonderilenMailKullanicilars { get; set; }
        public virtual DbSet<GonderilenMailler> GonderilenMaillers { get; set; }
        public virtual DbSet<HaftaGunleri> HaftaGunleris { get; set; }
        public virtual DbSet<Kampusler> Kampuslers { get; set; }
        public virtual DbSet<KayitDurumlari> KayitDurumlaris { get; set; }
        public virtual DbSet<KayitSilmeAyarlar> KayitSilmeAyarlars { get; set; }
        public virtual DbSet<KayitSilmeBasvuru> KayitSilmeBasvurus { get; set; }
        public virtual DbSet<KayitSilmeDurumlari> KayitSilmeDurumlaris { get; set; }
        public virtual DbSet<KullaniciEnstituYetkileri> KullaniciEnstituYetkileris { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<KullaniciOgrenimleri> KullaniciOgrenimleris { get; set; }
        public virtual DbSet<KullaniciProgramlari> KullaniciProgramlaris { get; set; }
        public virtual DbSet<KullaniciTipleri> KullaniciTipleris { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MailSablonlari> MailSablonlaris { get; set; }
        public virtual DbSet<MailSablonlariEkleri> MailSablonlariEkleris { get; set; }
        public virtual DbSet<MailSablonTipleri> MailSablonTipleris { get; set; }
        public virtual DbSet<MedeniHaller> MedeniHallers { get; set; }
        public virtual DbSet<Menuler> Menulers { get; set; }
        public virtual DbSet<MesajEkleri> MesajEkleris { get; set; }
        public virtual DbSet<MesajKategorileri> MesajKategorileris { get; set; }
        public virtual DbSet<Mesajlar> Mesajlars { get; set; }
        public virtual DbSet<MezuniyetAyarlar> MezuniyetAyarlars { get; set; }
        public virtual DbSet<MezuniyetBasvurulari> MezuniyetBasvurularis { get; set; }
        public virtual DbSet<MezuniyetBasvurulariTezDosyalari> MezuniyetBasvurulariTezDosyalaris { get; set; }
        public virtual DbSet<MezuniyetBasvurulariTezTeslimFormlari> MezuniyetBasvurulariTezTeslimFormlaris { get; set; }
        public virtual DbSet<MezuniyetBasvurulariYayin> MezuniyetBasvurulariYayins { get; set; }
        public virtual DbSet<MezuniyetJuriOneriFormlari> MezuniyetJuriOneriFormlaris { get; set; }
        public virtual DbSet<MezuniyetJuriOneriFormuJurileri> MezuniyetJuriOneriFormuJurileris { get; set; }
        public virtual DbSet<MezuniyetSinavDurumlari> MezuniyetSinavDurumlaris { get; set; }
        public virtual DbSet<MezuniyetSureci> MezuniyetSurecis { get; set; }
        public virtual DbSet<MezuniyetSureciKriterMuafOgrenciler> MezuniyetSureciKriterMuafOgrencilers { get; set; }
        public virtual DbSet<MezuniyetSureciOgrenimTipKriterleri> MezuniyetSureciOgrenimTipKriterleris { get; set; }
        public virtual DbSet<MezuniyetSureciOtoMail> MezuniyetSureciOtoMails { get; set; }
        public virtual DbSet<MezuniyetSureciOtoMailGonderilenler> MezuniyetSureciOtoMailGonderilenlers { get; set; }
        public virtual DbSet<MezuniyetSureciYayinTurleri> MezuniyetSureciYayinTurleris { get; set; }
        public virtual DbSet<MezuniyetSureciYonetmelikleri> MezuniyetSureciYonetmelikleris { get; set; }
        public virtual DbSet<MezuniyetSureciYonetmelikleriOT> MezuniyetSureciYonetmelikleriOTs { get; set; }
        public virtual DbSet<MezuniyetYayinBelgeTurleri> MezuniyetYayinBelgeTurleris { get; set; }
        public virtual DbSet<MezuniyetYayinIndexTurleri> MezuniyetYayinIndexTurleris { get; set; }
        public virtual DbSet<MezuniyetYayinKontrolDurumlari> MezuniyetYayinKontrolDurumlaris { get; set; }
        public virtual DbSet<MezuniyetYayinLinkTurleri> MezuniyetYayinLinkTurleris { get; set; }
        public virtual DbSet<MezuniyetYayinMetinTurleri> MezuniyetYayinMetinTurleris { get; set; }
        public virtual DbSet<MezuniyetYayinProjeTurleri> MezuniyetYayinProjeTurleris { get; set; }
        public virtual DbSet<MezuniyetYayinTurleri> MezuniyetYayinTurleris { get; set; }
        public virtual DbSet<MezuniyetYonetmelikleri> MezuniyetYonetmelikleris { get; set; }
        public virtual DbSet<MezuniyetYonetmelikleriOT> MezuniyetYonetmelikleriOTs { get; set; }
        public virtual DbSet<Mulakat> Mulakats { get; set; }
        public virtual DbSet<MulakatDetay> MulakatDetays { get; set; }
        public virtual DbSet<MulakatJuri> MulakatJuris { get; set; }
        public virtual DbSet<MulakatSinavTurleri> MulakatSinavTurleris { get; set; }
        public virtual DbSet<MulakatSonuclari> MulakatSonuclaris { get; set; }
        public virtual DbSet<MulakatSonucTipleri> MulakatSonucTipleris { get; set; }
        public virtual DbSet<NotSistemleri> NotSistemleris { get; set; }
        public virtual DbSet<OgrenciBolumleri> OgrenciBolumleris { get; set; }
        public virtual DbSet<OgrenimDurumlari> OgrenimDurumlaris { get; set; }
        public virtual DbSet<OgrenimTipleri> OgrenimTipleris { get; set; }
        public virtual DbSet<OzelNotTipleri> OzelNotTipleris { get; set; }
        public virtual DbSet<OzelTarihTipleri> OzelTarihTipleris { get; set; }
        public virtual DbSet<Roller> Rollers { get; set; }
        public virtual DbSet<Sehirler> Sehirlers { get; set; }
        public virtual DbSet<ServiceLog> ServiceLogs { get; set; }
        public virtual DbSet<ServiceRole> ServiceRoles { get; set; }
        public virtual DbSet<ServiceUser> ServiceUsers { get; set; }
        public virtual DbSet<ServiceUserRole> ServiceUserRoles { get; set; }
        public virtual DbSet<SikcaSorulanSorular> SikcaSorulanSorulars { get; set; }
        public virtual DbSet<SinavDilleri> SinavDilleris { get; set; }
        public virtual DbSet<SinavNotlari> SinavNotlaris { get; set; }
        public virtual DbSet<SinavTipGruplari> SinavTipGruplaris { get; set; }
        public virtual DbSet<SinavTipleri> SinavTipleris { get; set; }
        public virtual DbSet<SinavTipleriOT_SNA> SinavTipleriOT_SNA { get; set; }
        public virtual DbSet<SinavTipleriOT_SNA_OT> SinavTipleriOT_SNA_OT { get; set; }
        public virtual DbSet<SinavTipleriOT_SNA_PR> SinavTipleriOT_SNA_PR { get; set; }
        public virtual DbSet<SinavTipleriOTNotAraliklari> SinavTipleriOTNotAraliklaris { get; set; }
        public virtual DbSet<SinavTipleriOTNotAraliklariGecersizProgramlar> SinavTipleriOTNotAraliklariGecersizProgramlars { get; set; }
        public virtual DbSet<SinavTiplerSubSinavAralik> SinavTiplerSubSinavAraliks { get; set; }
        public virtual DbSet<SistemBilgilendirme> SistemBilgilendirmes { get; set; }
        public virtual DbSet<SistemDilleri> SistemDilleris { get; set; }
        public virtual DbSet<SRDurumlari> SRDurumlaris { get; set; }
        public virtual DbSet<SROzelTanimlar> SROzelTanimlars { get; set; }
        public virtual DbSet<SROzelTanimTipleri> SROzelTanimTipleris { get; set; }
        public virtual DbSet<SRSaatler> SRSaatlers { get; set; }
        public virtual DbSet<SRSalonDurumlari> SRSalonDurumlaris { get; set; }
        public virtual DbSet<SRSalonlar> SRSalonlars { get; set; }
        public virtual DbSet<SRSalonTalepTipleri> SRSalonTalepTipleris { get; set; }
        public virtual DbSet<SRTaleplerJuri> SRTaleplerJuris { get; set; }
        public virtual DbSet<SRTalepTipleri> SRTalepTipleris { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TalepArGorStatuleri> TalepArGorStatuleris { get; set; }
        public virtual DbSet<TalepDurumlari> TalepDurumlaris { get; set; }
        public virtual DbSet<TalepGelenTalepBelgeleri> TalepGelenTalepBelgeleris { get; set; }
        public virtual DbSet<TalepGelenTalepler> TalepGelenTaleplers { get; set; }
        public virtual DbSet<TalepSureciTalepTipleri> TalepSureciTalepTipleris { get; set; }
        public virtual DbSet<TalepSurecleri> TalepSurecleris { get; set; }
        public virtual DbSet<TalepTipleri> TalepTipleris { get; set; }
        public virtual DbSet<TDOAyarlar> TDOAyarlars { get; set; }
        public virtual DbSet<TDOBasvuru> TDOBasvurus { get; set; }
        public virtual DbSet<TDOBasvuruDanisman> TDOBasvuruDanismen { get; set; }
        public virtual DbSet<TDOBasvuruEsDanisman> TDOBasvuruEsDanismen { get; set; }
        public virtual DbSet<TDODanismanTalepTipleri> TDODanismanTalepTipleris { get; set; }
        public virtual DbSet<TIAyarlar> TIAyarlars { get; set; }
        public virtual DbSet<TIBasvuru> TIBasvurus { get; set; }
        public virtual DbSet<TIBasvuruAraRapor> TIBasvuruAraRapors { get; set; }
        public virtual DbSet<TIBasvuruAraRaporDurumlari> TIBasvuruAraRaporDurumlaris { get; set; }
        public virtual DbSet<TIBasvuruAraRaporKomite> TIBasvuruAraRaporKomites { get; set; }
        public virtual DbSet<TijBasvuru> TijBasvurus { get; set; }
        public virtual DbSet<TijBasvuruOneri> TijBasvuruOneris { get; set; }
        public virtual DbSet<TijBasvuruOneriJuriler> TijBasvuruOneriJurilers { get; set; }
        public virtual DbSet<TijDegisiklikTipleri> TijDegisiklikTipleris { get; set; }
        public virtual DbSet<TijFormTipleri> TijFormTipleris { get; set; }
        public virtual DbSet<ToBasvuru> ToBasvurus { get; set; }
        public virtual DbSet<ToBasvuruSavunma> ToBasvuruSavunmas { get; set; }
        public virtual DbSet<ToBasvuruSavunmaDurumlari> ToBasvuruSavunmaDurumlaris { get; set; }
        public virtual DbSet<ToBasvuruSavunmaKomite> ToBasvuruSavunmaKomites { get; set; }
        public virtual DbSet<Universiteler> Universitelers { get; set; }
        public virtual DbSet<Unvanlar> Unvanlars { get; set; }
        public virtual DbSet<Uyruklar> Uyruklars { get; set; }
        public virtual DbSet<WsSinavCekimTipleri> WsSinavCekimTipleris { get; set; }
        public virtual DbSet<WsSinavCekipTipDetay> WsSinavCekipTipDetays { get; set; }
        public virtual DbSet<YaziSablonlari> YaziSablonlaris { get; set; }
        public virtual DbSet<YaziSablonlariEkleri> YaziSablonlariEkleris { get; set; }
        public virtual DbSet<YaziSablonTipleri> YaziSablonTipleris { get; set; }
        public virtual DbSet<YeterlikBasvuru> YeterlikBasvurus { get; set; }
        public virtual DbSet<YeterlikBasvuruJuriUyeleri> YeterlikBasvuruJuriUyeleris { get; set; }
        public virtual DbSet<YeterlikBasvuruKomiteler> YeterlikBasvuruKomitelers { get; set; }
        public virtual DbSet<YeterlikSureci> YeterlikSurecis { get; set; }
        public virtual DbSet<YeterlikSureciKriterMuafOgrenciler> YeterlikSureciKriterMuafOgrencilers { get; set; }
        public virtual DbSet<YeterlikSurecOgrenimTipleri> YeterlikSurecOgrenimTipleris { get; set; }
        public virtual DbSet<YetkiGruplari> YetkiGruplaris { get; set; }
        public virtual DbSet<YetkiGrupRolleri> YetkiGrupRolleris { get; set; }
        public virtual DbSet<ZamanTipleri> ZamanTipleris { get; set; }
        public virtual DbSet<vW_ProgramBasvuruSonucSayisal> vW_ProgramBasvuruSonucSayisal { get; set; }
        public virtual DbSet<Programlar> Programlars { get; set; }
        public virtual DbSet<SRTalepleri> SRTalepleris { get; set; }
    
        public virtual ObjectResult<sp_SearchMailsFullText_Result> sp_SearchMailsFullText(string enstituKodList, Nullable<bool> isEkVar, string konu, string enstituKod, Nullable<System.DateTime> tarih, string mailGonderen, Nullable<int> startRow, Nullable<int> pageSize, ObjectParameter totalCount)
        {
            var enstituKodListParameter = enstituKodList != null ?
                new ObjectParameter("EnstituKodList", enstituKodList) :
                new ObjectParameter("EnstituKodList", typeof(string));
    
            var isEkVarParameter = isEkVar.HasValue ?
                new ObjectParameter("IsEkVar", isEkVar) :
                new ObjectParameter("IsEkVar", typeof(bool));
    
            var konuParameter = konu != null ?
                new ObjectParameter("Konu", konu) :
                new ObjectParameter("Konu", typeof(string));
    
            var enstituKodParameter = enstituKod != null ?
                new ObjectParameter("EnstituKod", enstituKod) :
                new ObjectParameter("EnstituKod", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var mailGonderenParameter = mailGonderen != null ?
                new ObjectParameter("MailGonderen", mailGonderen) :
                new ObjectParameter("MailGonderen", typeof(string));
    
            var startRowParameter = startRow.HasValue ?
                new ObjectParameter("StartRow", startRow) :
                new ObjectParameter("StartRow", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchMailsFullText_Result>("sp_SearchMailsFullText", enstituKodListParameter, isEkVarParameter, konuParameter, enstituKodParameter, tarihParameter, mailGonderenParameter, startRowParameter, pageSizeParameter, totalCount);
        }
    
        public virtual ObjectResult<sp_SearchUsersOptimized_Result> sp_SearchUsersOptimized(string enstituKodList, string enstituKod, string adSoyad, Nullable<bool> isAktif, Nullable<int> kullaniciTipID, Nullable<int> birimID, Nullable<int> ogrenimTipKod, Nullable<bool> isEkYetkiVar, Nullable<int> ogrenimDurumID, Nullable<int> cinsiyetID, Nullable<int> yetkiGrupID, Nullable<int> startRow, Nullable<int> pageSize, string sortColumn, string sortDirection, ObjectParameter totalCount, ObjectParameter aktifCount, ObjectParameter pasifCount)
        {
            var enstituKodListParameter = enstituKodList != null ?
                new ObjectParameter("EnstituKodList", enstituKodList) :
                new ObjectParameter("EnstituKodList", typeof(string));
    
            var enstituKodParameter = enstituKod != null ?
                new ObjectParameter("EnstituKod", enstituKod) :
                new ObjectParameter("EnstituKod", typeof(string));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var isAktifParameter = isAktif.HasValue ?
                new ObjectParameter("IsAktif", isAktif) :
                new ObjectParameter("IsAktif", typeof(bool));
    
            var kullaniciTipIDParameter = kullaniciTipID.HasValue ?
                new ObjectParameter("KullaniciTipID", kullaniciTipID) :
                new ObjectParameter("KullaniciTipID", typeof(int));
    
            var birimIDParameter = birimID.HasValue ?
                new ObjectParameter("BirimID", birimID) :
                new ObjectParameter("BirimID", typeof(int));
    
            var ogrenimTipKodParameter = ogrenimTipKod.HasValue ?
                new ObjectParameter("OgrenimTipKod", ogrenimTipKod) :
                new ObjectParameter("OgrenimTipKod", typeof(int));
    
            var isEkYetkiVarParameter = isEkYetkiVar.HasValue ?
                new ObjectParameter("IsEkYetkiVar", isEkYetkiVar) :
                new ObjectParameter("IsEkYetkiVar", typeof(bool));
    
            var ogrenimDurumIDParameter = ogrenimDurumID.HasValue ?
                new ObjectParameter("OgrenimDurumID", ogrenimDurumID) :
                new ObjectParameter("OgrenimDurumID", typeof(int));
    
            var cinsiyetIDParameter = cinsiyetID.HasValue ?
                new ObjectParameter("CinsiyetID", cinsiyetID) :
                new ObjectParameter("CinsiyetID", typeof(int));
    
            var yetkiGrupIDParameter = yetkiGrupID.HasValue ?
                new ObjectParameter("YetkiGrupID", yetkiGrupID) :
                new ObjectParameter("YetkiGrupID", typeof(int));
    
            var startRowParameter = startRow.HasValue ?
                new ObjectParameter("StartRow", startRow) :
                new ObjectParameter("StartRow", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchUsersOptimized_Result>("sp_SearchUsersOptimized", enstituKodListParameter, enstituKodParameter, adSoyadParameter, isAktifParameter, kullaniciTipIDParameter, birimIDParameter, ogrenimTipKodParameter, isEkYetkiVarParameter, ogrenimDurumIDParameter, cinsiyetIDParameter, yetkiGrupIDParameter, startRowParameter, pageSizeParameter, sortColumnParameter, sortDirectionParameter, totalCount, aktifCount, pasifCount);
        }
    }
}
