//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetBasvurulariTezDosyalari
    {
        public int MezuniyetBasvurulariTezDosyaID { get; set; }
        public System.Guid RowID { get; set; }
        public int SiraNo { get; set; }
        public int MezuniyetBasvurulariID { get; set; }
        public string TezDosyaAdi { get; set; }
        public string TezDosyaYolu { get; set; }
        public Nullable<bool> IsOnaylandiOrDuzeltme { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> YuklemeTarihi { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public Nullable<int> OnayYapanID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual MezuniyetBasvurulari MezuniyetBasvurulari { get; set; }
    }
}
