//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciOtoMail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetSureciOtoMail()
        {
            this.MezuniyetSureciOtoMailGonderilenlers = new HashSet<MezuniyetSureciOtoMailGonderilenler>();
        }
    
        public int MezuniyetSureciOtoMailID { get; set; }
        public int OtoMailID { get; set; }
        public int MezuniyetSurecID { get; set; }
        public int MailSablonTipID { get; set; }
        public int Sure { get; set; }
        public bool IsAktif { get; set; }
    
        public virtual MezuniyetSureci MezuniyetSureci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureciOtoMailGonderilenler> MezuniyetSureciOtoMailGonderilenlers { get; set; }
    }
}
