//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetYayinMetinTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetYayinMetinTurleri()
        {
            this.MezuniyetYayinTurleris = new HashSet<MezuniyetYayinTurleri>();
            this.MezuniyetBasvurulariYayins = new HashSet<MezuniyetBasvurulariYayin>();
        }
    
        public int MezuniyetYayinMetinTurID { get; set; }
        public string MetinTurAdi { get; set; }
        public bool IsAktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYayinTurleri> MezuniyetYayinTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulariYayin> MezuniyetBasvurulariYayins { get; set; }
    }
}
