//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetYayinTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetYayinTurleri()
        {
            this.MezuniyetSureciYonetmelikleriOTs = new HashSet<MezuniyetSureciYonetmelikleriOT>();
            this.MezuniyetYonetmelikleriOTs = new HashSet<MezuniyetYonetmelikleriOT>();
            this.MezuniyetBasvurulariYayins = new HashSet<MezuniyetBasvurulariYayin>();
        }
    
        public int MezuniyetYayinTurID { get; set; }
        public bool TarihIstensin { get; set; }
        public Nullable<int> MezuniyetYayinBelgeTurID { get; set; }
        public bool BelgeZorunlu { get; set; }
        public Nullable<int> KaynakMezuniyetYayinLinkTurID { get; set; }
        public bool KaynakLinkiZorunlu { get; set; }
        public Nullable<int> MezuniyetYayinMetinTurID { get; set; }
        public bool MetinZorunlu { get; set; }
        public Nullable<int> YayinMezuniyetYayinLinkTurID { get; set; }
        public bool YayinLinkiZorunlu { get; set; }
        public bool YayinIndexTurIstensin { get; set; }
        public bool YayinKabulEdilmisMakaleIstensin { get; set; }
        public bool YayinYazarlarIstensin { get; set; }
        public bool YayinDergiAdiIstensin { get; set; }
        public bool YayinYilCiltSayiIstensin { get; set; }
        public bool YayinProjeTurIstensin { get; set; }
        public bool YayinProjeEkibiIstensin { get; set; }
        public bool YayinMevcutDurumIstensin { get; set; }
        public bool YayinDeatKurulusIstensin { get; set; }
        public bool IsTarihAraligiIstensin { get; set; }
        public bool YayinEtkinlikAdiIstensin { get; set; }
        public bool YayinYerBilgisiIstensin { get; set; }
        public string MezuniyetYayinTurAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureciYonetmelikleriOT> MezuniyetSureciYonetmelikleriOTs { get; set; }
        public virtual MezuniyetYayinLinkTurleri MezuniyetYayinLinkTurleri { get; set; }
        public virtual MezuniyetYayinLinkTurleri MezuniyetYayinLinkTurleri1 { get; set; }
        public virtual MezuniyetYayinMetinTurleri MezuniyetYayinMetinTurleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetYonetmelikleriOT> MezuniyetYonetmelikleriOTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulariYayin> MezuniyetBasvurulariYayins { get; set; }
    }
}
