//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciKriterMuafOgrenciler
    {
        public int MezuniyetSurecKriterMuafOgrenciID { get; set; }
        public int MezuniyetSurecID { get; set; }
        public int KullaniciID { get; set; }
        public int IslemYapanID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual MezuniyetSureci MezuniyetSureci { get; set; }
    }
}
