//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciOtoMailGonderilenler
    {
        public int MezuniyetSureciOtoMailGonderilenID { get; set; }
        public int MezuniyetSureciOtoMailID { get; set; }
        public int MezuniyetBasvurulariID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual MezuniyetSureciOtoMail MezuniyetSureciOtoMail { get; set; }
    }
}
