//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetYayinKontrolDurumlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetYayinKontrolDurumlari()
        {
            this.MezuniyetBasvurularis = new HashSet<MezuniyetBasvurulari>();
        }
    
        public int MezuniyetYayinKontrolDurumID { get; set; }
        public string ClassName { get; set; }
        public string Color { get; set; }
        public bool BasvuranGorsun { get; set; }
        public bool YoneticiGorsun { get; set; }
        public string MezuniyetYayinKontrolDurumAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulari> MezuniyetBasvurularis { get; set; }
    }
}
