//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetBasvurulariYayin
    {
        public int MezuniyetBasvurulariYayinID { get; set; }
        public int MezuniyetBasvurulariID { get; set; }
        public int MezuniyetYayinTurID { get; set; }
        public Nullable<bool> DanismanIsmiVar { get; set; }
        public Nullable<bool> TezIcerikUyumuVar { get; set; }
        public Nullable<bool> Onaylandi { get; set; }
        public string RetAciklamasi { get; set; }
        public Nullable<bool> Yayinlanmis { get; set; }
        public Nullable<System.DateTime> MezuniyetYayinTarih { get; set; }
        public string YayinBasligi { get; set; }
        public Nullable<int> MezuniyetYayinBelgeTurID { get; set; }
        public string MezuniyetYayinBelgeAdi { get; set; }
        public string MezuniyetYayinBelgeDosyaYolu { get; set; }
        public Nullable<int> MezuniyetYayinKaynakLinkTurID { get; set; }
        public string MezuniyetYayinKaynakLinki { get; set; }
        public Nullable<int> MezuniyetYayinMetinTurID { get; set; }
        public string MezuniyetYayinMetniBelgeAdi { get; set; }
        public string MezuniyetYayinMetniBelgeYolu { get; set; }
        public Nullable<int> MezuniyetYayinLinkTurID { get; set; }
        public string MezuniyetYayinLinki { get; set; }
        public Nullable<int> MezuniyetYayinIndexTurID { get; set; }
        public string MezuniyetYayinKabulEdilmisMakaleAdi { get; set; }
        public string MezuniyetYayinKabulEdilmisMakaleDosyaYolu { get; set; }
        public string YazarAdi { get; set; }
        public string DergiAdi { get; set; }
        public string YilCiltSayiSS { get; set; }
        public Nullable<int> MezuniyetYayinProjeTurID { get; set; }
        public Nullable<bool> IsProjeTamamlandiOrDevamEdiyor { get; set; }
        public string ProjeEkibi { get; set; }
        public string ProjeDeatKurulus { get; set; }
        public string TarihAraligi { get; set; }
        public string EtkinlikAdi { get; set; }
        public string YerBilgisi { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual MezuniyetBasvurulari MezuniyetBasvurulari { get; set; }
        public virtual MezuniyetYayinBelgeTurleri MezuniyetYayinBelgeTurleri { get; set; }
        public virtual MezuniyetYayinIndexTurleri MezuniyetYayinIndexTurleri { get; set; }
        public virtual MezuniyetYayinLinkTurleri MezuniyetYayinLinkTurleri { get; set; }
        public virtual MezuniyetYayinMetinTurleri MezuniyetYayinMetinTurleri { get; set; }
        public virtual MezuniyetYayinProjeTurleri MezuniyetYayinProjeTurleri { get; set; }
        public virtual MezuniyetYayinTurleri MezuniyetYayinTurleri { get; set; }
    }
}
