//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciYonetmelikleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetSureciYonetmelikleri()
        {
            this.MezuniyetSureciYonetmelikleriOTs = new HashSet<MezuniyetSureciYonetmelikleriOT>();
        }
    
        public int MezuniyetSureciYonetmelikID { get; set; }
        public string EnstituKod { get; set; }
        public int MezuniyetSurecID { get; set; }
        public int TarihKriterID { get; set; }
        public int BaslangicYil { get; set; }
        public int BitisYil { get; set; }
        public int DonemID { get; set; }
        public Nullable<int> BaslangicYilB { get; set; }
        public Nullable<int> BitisYilB { get; set; }
        public Nullable<int> DonemIDB { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Enstituler Enstituler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetSureciYonetmelikleriOT> MezuniyetSureciYonetmelikleriOTs { get; set; }
    }
}
