//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MulakatDetay
    {
        public int MulakatDetayID { get; set; }
        public int MulakatID { get; set; }
        public int KampusID { get; set; }
        public int MulakatSinavTurID { get; set; }
        public int YuzdeOran { get; set; }
        public System.DateTime SinavTarihi { get; set; }
        public string YerAdi { get; set; }
    
        public virtual Kampusler Kampusler { get; set; }
        public virtual Mulakat Mulakat { get; set; }
        public virtual MulakatSinavTurleri MulakatSinavTurleri { get; set; }
    }
}
