//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MulakatSinavTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MulakatSinavTurleri()
        {
            this.BasvuruSurecMulakatSinavTurleris = new HashSet<BasvuruSurecMulakatSinavTurleri>();
            this.MulakatDetays = new HashSet<MulakatDetay>();
        }
    
        public int MulakatSinavTurID { get; set; }
        public int YuzdeOran { get; set; }
        public string MulakatSinavTurAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecMulakatSinavTurleri> BasvuruSurecMulakatSinavTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatDetay> MulakatDetays { get; set; }
    }
}
