//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programlar2Obs
    {
        public int TableId { get; set; }
        public string FakulteKod { get; set; }
        public string FakulteAd { get; set; }
        public string BolumId { get; set; }
        public string BolumKod { get; set; }
        public string BolumAd { get; set; }
        public string ProgramId { get; set; }
        public string ProgramKod { get; set; }
        public string ProgramAd { get; set; }
        public string ProgramTur { get; set; }
        public string ProgramTip { get; set; }
        public string NormalSure { get; set; }
        public string AzamiSure { get; set; }
    }
}
