//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programlar2
    {
        public string ProgramKod { get; set; }
        public int AnabilimDaliID { get; set; }
        public string AnabilimDaliKod { get; set; }
        public Nullable<int> ObsProgramId { get; set; }
        public bool Ingilizce { get; set; }
        public string ProgramAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
