//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int ServiceLogId { get; set; }
        public Nullable<int> ServiceUserID { get; set; }
        public string ServiceUserName { get; set; }
        public string MethodName { get; set; }
        public int IslemSuresiSn { get; set; }
        public System.DateTime LogTarihi { get; set; }
    }
}
