//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavTipleriOTNotAraliklariGecersizProgramlar
    {
        public int SinavTipleriOTNotAraliklariGecersizProgramlarID { get; set; }
        public int SinavTipleriOTNotAralikID { get; set; }
        public string ProgramKod { get; set; }
    
        public virtual Programlar Programlar { get; set; }
        public virtual SinavTipleriOTNotAraliklari SinavTipleriOTNotAraliklari { get; set; }
    }
}
