//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavTipleriOT_SNA_PR
    {
        public int SinavTipleriOT_SNA_PRID { get; set; }
        public int SinavTipleriOT_SNAID { get; set; }
        public string ProgramKod { get; set; }
    
        public virtual SinavTipleriOT_SNA SinavTipleriOT_SNA { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
