//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinavTipleri()
        {
            this.BasvurularSinavBilgis = new HashSet<BasvurularSinavBilgi>();
            this.BasvuruSurecSinavTipleris = new HashSet<BasvuruSurecSinavTipleri>();
            this.BasvuruSurecSinavTipleriOT_SNA = new HashSet<BasvuruSurecSinavTipleriOT_SNA>();
            this.BasvuruSurecSinavTipleriOTNotAraliklaris = new HashSet<BasvuruSurecSinavTipleriOTNotAraliklari>();
            this.SinavNotlaris = new HashSet<SinavNotlari>();
            this.SinavTipleriOT_SNA = new HashSet<SinavTipleriOT_SNA>();
            this.SinavTipleriOTNotAraliklaris = new HashSet<SinavTipleriOTNotAraliklari>();
            this.SinavTiplerSubSinavAraliks = new HashSet<SinavTiplerSubSinavAralik>();
            this.TDOBasvuruDanismen = new HashSet<TDOBasvuruDanisman>();
        }
    
        public int SinavTipID { get; set; }
        public string EnstituKod { get; set; }
        public int SinavTipGrupID { get; set; }
        public int SinavTipKod { get; set; }
        public bool OzelNot { get; set; }
        public Nullable<int> OzelNotTipID { get; set; }
        public string SinavAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularSinavBilgi> BasvurularSinavBilgis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleri> BasvuruSurecSinavTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOT_SNA> BasvuruSurecSinavTipleriOT_SNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOTNotAraliklari> BasvuruSurecSinavTipleriOTNotAraliklaris { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OzelNotTipleri OzelNotTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavNotlari> SinavNotlaris { get; set; }
        public virtual SinavTipGruplari SinavTipGruplari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleriOT_SNA> SinavTipleriOT_SNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleriOTNotAraliklari> SinavTipleriOTNotAraliklaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTiplerSubSinavAralik> SinavTiplerSubSinavAraliks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuruDanisman> TDOBasvuruDanismen { get; set; }
    }
}
