//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSalonDurumlari
    {
        public int SRSalonDurumID { get; set; }
        public bool IsSalonInfo { get; set; }
        public bool IsYeniKayit { get; set; }
        public bool Secilebilir { get; set; }
        public string Color { get; set; }
        public string SalonDurumAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
