//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalepSureciTalepTipleri
    {
        public int TalepSureciTalepTipID { get; set; }
        public int TalepSurecID { get; set; }
        public int TalepTipID { get; set; }
        public bool IsBelgeYuklemeVar { get; set; }
        public bool IsTaahhutIsteniyor { get; set; }
    
        public virtual TalepSurecleri TalepSurecleri { get; set; }
        public virtual TalepTipleri TalepTipleri { get; set; }
    }
}
