//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDOBasvuruDanisman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDOBasvuruDanisman()
        {
            this.TDOBasvurus = new HashSet<TDOBasvuru>();
            this.TDOBasvuruEsDanismen = new HashSet<TDOBasvuruEsDanisman>();
        }
    
        public int TDOBasvuruDanismanID { get; set; }
        public bool IsObsData { get; set; }
        public System.Guid UniqueID { get; set; }
        public int TDODanismanTalepTipID { get; set; }
        public int TDOBasvuruID { get; set; }
        public string FormKodu { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int DonemBaslangicYil { get; set; }
        public int DonemID { get; set; }
        public bool IsTezDiliTr { get; set; }
        public string TezBaslikTr { get; set; }
        public string TezBaslikEn { get; set; }
        public Nullable<bool> IsYeniTezDiliTr { get; set; }
        public string YeniTezBaslikTr { get; set; }
        public string YeniTezBaslikEn { get; set; }
        public Nullable<int> SinavTipID { get; set; }
        public string SinavAdi { get; set; }
        public Nullable<int> SinavYili { get; set; }
        public string SinavPuani { get; set; }
        public Nullable<int> VarolanTezDanismanID { get; set; }
        public string VarolanTDAdSoyad { get; set; }
        public string VarolanTDUnvanAdi { get; set; }
        public string VarolanTDAnabilimDaliAdi { get; set; }
        public string VarolanTDProgramAdi { get; set; }
        public Nullable<bool> VarolanDanismanOnayladi { get; set; }
        public Nullable<System.DateTime> VarolanDanismanOnayTarihi { get; set; }
        public string VarolanDanismanOnaylanmadiAciklama { get; set; }
        public int TezDanismanID { get; set; }
        public string TDAdSoyad { get; set; }
        public string TDUnvanAdi { get; set; }
        public Nullable<int> TDAnabilimDaliID { get; set; }
        public string TDAnabilimDaliAdi { get; set; }
        public string TDProgramKod { get; set; }
        public string TDProgramAdi { get; set; }
        public Nullable<int> TDOgrenciSayisiYL { get; set; }
        public Nullable<int> TDOgrenciSayisiDR { get; set; }
        public Nullable<int> TDTezSayisiYL { get; set; }
        public Nullable<int> TDTezSayisiDR { get; set; }
        public Nullable<bool> DanismanOnayladi { get; set; }
        public Nullable<System.DateTime> DanismanOnayTarihi { get; set; }
        public string DanismanOnaylanmadiAciklama { get; set; }
        public Nullable<bool> EYKYaGonderildi { get; set; }
        public Nullable<int> EYKYaGonderildiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaGonderildiIslemTarihi { get; set; }
        public string EYKYaGonderimDurumAciklamasi { get; set; }
        public Nullable<bool> EYKYaHazirlandi { get; set; }
        public Nullable<int> EYKYaHazirlandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaHazirlandiIslemTarihi { get; set; }
        public Nullable<bool> EYKDaOnaylandi { get; set; }
        public Nullable<int> EYKDaOnaylandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKDaOnaylandiOnayTarihi { get; set; }
        public string EYKDaOnaylanmadiDurumAciklamasi { get; set; }
        public string Gerekce { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual AnabilimDallari AnabilimDallari { get; set; }
        public virtual Donemler Donemler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Programlar Programlar { get; set; }
        public virtual SinavTipleri SinavTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuru> TDOBasvurus { get; set; }
        public virtual TDOBasvuru TDOBasvuru { get; set; }
        public virtual TDODanismanTalepTipleri TDODanismanTalepTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuruEsDanisman> TDOBasvuruEsDanismen { get; set; }
    }
}
