//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIBasvuruAraRaporDurumlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIBasvuruAraRaporDurumlari()
        {
            this.TIBasvuruAraRapors = new HashSet<TIBasvuruAraRapor>();
        }
    
        public int TIBasvuruAraRaporDurumID { get; set; }
        public string TIBasvuruAraRaporDurumAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuruAraRapor> TIBasvuruAraRapors { get; set; }
    }
}
