//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIBasvuruAraRapor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIBasvuruAraRapor()
        {
            this.SRTalepleris = new HashSet<SRTalepleri>();
            this.TIBasvurus = new HashSet<TIBasvuru>();
            this.TIBasvuruAraRaporKomites = new HashSet<TIBasvuruAraRaporKomite>();
        }
    
        public int TIBasvuruAraRaporID { get; set; }
        public int TIBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string FormKodu { get; set; }
        public string BasvuruSonDonemSecilecekDersKodlari { get; set; }
        public int TIBasvuruAraRaporDurumID { get; set; }
        public Nullable<int> TezDanismanID { get; set; }
        public int AraRaporSayisi { get; set; }
        public System.DateTime RaporTarihi { get; set; }
        public int DonemBaslangicYil { get; set; }
        public int DonemID { get; set; }
        public bool IsTezDiliTr { get; set; }
        public string TezBaslikTr { get; set; }
        public string TezBaslikEn { get; set; }
        public bool IsTezBasligiDegisti { get; set; }
        public string YeniTezBaslikTr { get; set; }
        public string YeniTezBaslikEn { get; set; }
        public string TezBasligiDegisimGerekcesi { get; set; }
        public string TICalismaRaporDosyaAdi { get; set; }
        public string TICalismaRaporDosyaYolu { get; set; }
        public bool IsYokDrBursiyeriVar { get; set; }
        public string YokDrOncelikliAlan { get; set; }
        public Nullable<System.DateTime> ToplantiBilgiGonderimTarihi { get; set; }
        public Nullable<System.DateTime> RSBaslatildiMailGonderimTarihi { get; set; }
        public Nullable<bool> IsOyBirligiOrCoklugu { get; set; }
        public Nullable<bool> IsBasariliOrBasarisiz { get; set; }
        public Nullable<System.DateTime> DegerlendirmeSonucMailTarihi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
        public bool IsTezDiliDegisecek { get; set; }
        public Nullable<bool> YeniTezDiliTr { get; set; }
        public string SinavAdi { get; set; }
        public string SinavPuani { get; set; }
        public Nullable<int> SinavYili { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepleri> SRTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuru> TIBasvurus { get; set; }
        public virtual TIBasvuru TIBasvuru { get; set; }
        public virtual TIBasvuruAraRaporDurumlari TIBasvuruAraRaporDurumlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuruAraRaporKomite> TIBasvuruAraRaporKomites { get; set; }
    }
}
