//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TijBasvuruOneriJuriler
    {
        public int TijBasvuruOneriJuriID { get; set; }
        public int TijBasvuruOneriID { get; set; }
        public bool IsYeniOrOnceki { get; set; }
        public int RowNum { get; set; }
        public bool IsTezDanismani { get; set; }
        public bool IsYtuIciJuri { get; set; }
        public string UnvanAdi { get; set; }
        public string AdSoyad { get; set; }
        public string EMail { get; set; }
        public Nullable<int> UniversiteID { get; set; }
        public string UniversiteAdi { get; set; }
        public string AnabilimdaliAdi { get; set; }
        public Nullable<bool> IsAsil { get; set; }
    
        public virtual TijBasvuruOneri TijBasvuruOneri { get; set; }
        public virtual Universiteler Universiteler { get; set; }
    }
}
