//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBasvuruSavunma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToBasvuruSavunma()
        {
            this.SRTalepleris = new HashSet<SRTalepleri>();
            this.ToBasvuruSavunmaKomites = new HashSet<ToBasvuruSavunmaKomite>();
        }
    
        public int ToBasvuruSavunmaID { get; set; }
        public int ToBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public int SavunmaNo { get; set; }
        public string FormKodu { get; set; }
        public Nullable<int> TezDanismanID { get; set; }
        public System.DateTime SavunmaBasvuruTarihi { get; set; }
        public int DonemBaslangicYil { get; set; }
        public int DonemID { get; set; }
        public bool IsTezDiliTr { get; set; }
        public string YeniTezBaslikTr { get; set; }
        public string YeniTezBaslikEn { get; set; }
        public string CalismaRaporDosyaAdi { get; set; }
        public string CalismaRaporDosyaYolu { get; set; }
        public bool IsYokDrBursiyeriVar { get; set; }
        public string YokDrOncelikliAlan { get; set; }
        public Nullable<System.DateTime> ToplantiBilgiGonderimTarihi { get; set; }
        public Nullable<System.DateTime> ToSavunmaBaslatildiMailGonderimTarihi { get; set; }
        public Nullable<bool> IsOyBirligiOrCoklugu { get; set; }
        public Nullable<int> ToBasvuruSavunmaDurumID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeSonucMailTarihi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepleri> SRTalepleris { get; set; }
        public virtual ToBasvuru ToBasvuru { get; set; }
        public virtual ToBasvuruSavunmaDurumlari ToBasvuruSavunmaDurumlari { get; set; }
        public virtual ToBasvuruSavunmaDurumlari ToBasvuruSavunmaDurumlari1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunmaKomite> ToBasvuruSavunmaKomites { get; set; }
    }
}
