//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBasvuruSavunmaDurumlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToBasvuruSavunmaDurumlari()
        {
            this.ToBasvuruSavunmas = new HashSet<ToBasvuruSavunma>();
            this.ToBasvuruSavunmas1 = new HashSet<ToBasvuruSavunma>();
            this.ToBasvuruSavunmaKomites = new HashSet<ToBasvuruSavunmaKomite>();
        }
    
        public int ToBasvuruSavunmaDurumID { get; set; }
        public string DurumAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunma> ToBasvuruSavunmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunma> ToBasvuruSavunmas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunmaKomite> ToBasvuruSavunmaKomites { get; set; }
    }
}
