//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBasvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToBasvuru()
        {
            this.ToBasvuruSavunmas = new HashSet<ToBasvuruSavunma>();
        }
    
        public int ToBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string EnstituKod { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string OgrenciNo { get; set; }
        public int OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public Nullable<int> KayitOgretimYiliBaslangic { get; set; }
        public Nullable<int> KayitOgretimYiliDonemID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> TezDanismanID { get; set; }
        public System.DateTime YeterlikSozluSinavTarihi { get; set; }
        public bool IsBasvuruKriterMuaf { get; set; }
        public Nullable<System.DateTime> IlkOneriBitisTarihi { get; set; }
        public Nullable<System.DateTime> IkinciOneriBitisTarihi { get; set; }
        public Nullable<System.DateTime> RetDuzeltmeBitisTarihi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Programlar Programlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToBasvuruSavunma> ToBasvuruSavunmas { get; set; }
    }
}
