//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WsSinavCekipTipDetay
    {
        public int WsSinavCekipTipDetayID { get; set; }
        public int WsSinavCekimTipID { get; set; }
        public string WsSinavCekimKod { get; set; }
        public string WsSinavCekimAd { get; set; }
    }
}
