//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class YaziSablonlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YaziSablonlari()
        {
            this.YaziSablonlariEkleris = new HashSet<YaziSablonlariEkleri>();
        }
    
        public int YaziSablonlariID { get; set; }
        public string EnstituKod { get; set; }
        public int YaziSablonTipID { get; set; }
        public string Konu { get; set; }
        public string Sablon { get; set; }
        public string SablonHtml { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual YaziSablonTipleri YaziSablonTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YaziSablonlariEkleri> YaziSablonlariEkleris { get; set; }
    }
}
