//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Ws_Persis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ws_Persis.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name kullanici from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/irfan_veri", ReplyAction="*")]
        LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponse irfan_veri(LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/irfan_veri", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponse> irfan_veriAsync(LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class irfan_veriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="irfan_veri", Namespace="http://tempuri.org/", Order=0)]
        public LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequestBody Body;
        
        public irfan_veriRequest() {
        }
        
        public irfan_veriRequest(LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class irfan_veriRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kullanici;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sifre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string adsoyad;
        
        public irfan_veriRequestBody() {
        }
        
        public irfan_veriRequestBody(string kullanici, string sifre, string adsoyad) {
            this.kullanici = kullanici;
            this.sifre = sifre;
            this.adsoyad = adsoyad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class irfan_veriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="irfan_veriResponse", Namespace="http://tempuri.org/", Order=0)]
        public LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponseBody Body;
        
        public irfan_veriResponse() {
        }
        
        public irfan_veriResponse(LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class irfan_veriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string irfan_veriResult;
        
        public irfan_veriResponseBody() {
        }
        
        public irfan_veriResponseBody(string irfan_veriResult) {
            this.irfan_veriResult = irfan_veriResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap>, LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponse LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap.irfan_veri(LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest request) {
            return base.Channel.irfan_veri(request);
        }
        
        public string irfan_veri(string kullanici, string sifre, string adsoyad) {
            LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest inValue = new LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest();
            inValue.Body = new LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequestBody();
            inValue.Body.kullanici = kullanici;
            inValue.Body.sifre = sifre;
            inValue.Body.adsoyad = adsoyad;
            LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponse retVal = ((LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap)(this)).irfan_veri(inValue);
            return retVal.Body.irfan_veriResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponse> LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap.irfan_veriAsync(LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest request) {
            return base.Channel.irfan_veriAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriResponse> irfan_veriAsync(string kullanici, string sifre, string adsoyad) {
            LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest inValue = new LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequest();
            inValue.Body = new LisansUstuBasvuruSistemi.Ws_Persis.irfan_veriRequestBody();
            inValue.Body.kullanici = kullanici;
            inValue.Body.sifre = sifre;
            inValue.Body.adsoyad = adsoyad;
            return ((LisansUstuBasvuruSistemi.Ws_Persis.Service1Soap)(this)).irfan_veriAsync(inValue);
        }
    }
}
