//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Ws_Kotalar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsisapplicantquota.net", ConfigurationName="Ws_Kotalar.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisapplicantquota.net/Kontenjanlar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisansUstuBasvuruSistemi.Ws_Kotalar.Quota[] Kontenjanlar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisapplicantquota.net/Kontenjanlar", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Kotalar.Quota[]> KontenjanlarAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsisapplicantquota.net")]
    public partial class Quota : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string branchidField;
        
        private int edutypeidField;
        
        private int fieldquotaField;
        
        private float minlesField;
        
        private float minagnoField;
        
        private string instidField;
        
        private int fieldoutquotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
                this.RaisePropertyChanged("Branchid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Edutypeid {
            get {
                return this.edutypeidField;
            }
            set {
                this.edutypeidField = value;
                this.RaisePropertyChanged("Edutypeid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Fieldquota {
            get {
                return this.fieldquotaField;
            }
            set {
                this.fieldquotaField = value;
                this.RaisePropertyChanged("Fieldquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float Minles {
            get {
                return this.minlesField;
            }
            set {
                this.minlesField = value;
                this.RaisePropertyChanged("Minles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float Minagno {
            get {
                return this.minagnoField;
            }
            set {
                this.minagnoField = value;
                this.RaisePropertyChanged("Minagno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Instid {
            get {
                return this.instidField;
            }
            set {
                this.instidField = value;
                this.RaisePropertyChanged("Instid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Fieldoutquota {
            get {
                return this.fieldoutquotaField;
            }
            set {
                this.fieldoutquotaField = value;
                this.RaisePropertyChanged("Fieldoutquota");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : LisansUstuBasvuruSistemi.Ws_Kotalar.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<LisansUstuBasvuruSistemi.Ws_Kotalar.WebServiceSoap>, LisansUstuBasvuruSistemi.Ws_Kotalar.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LisansUstuBasvuruSistemi.Ws_Kotalar.Quota[] Kontenjanlar() {
            return base.Channel.Kontenjanlar();
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Kotalar.Quota[]> KontenjanlarAsync() {
            return base.Channel.KontenjanlarAsync();
        }
    }
}
