//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Ws_Osym_1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServisSonuc", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiXmlYKHEH_S_P5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiYKHEH_S_P5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5))]
    public partial class ServisSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.SonucKodu SonucKoduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.SonucKodu SonucKodu {
            get {
                return this.SonucKoduField;
            }
            set {
                if ((this.SonucKoduField.Equals(value) != true)) {
                    this.SonucKoduField = value;
                    this.RaisePropertyChanged("SonucKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 : LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonuc {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.SinavSonucTemelBilgi[] SonucField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.SinavSonucTemelBilgi[] Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServisSonucOfSonucBilgiHtmlYKHEH_S_P5", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 : LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonuc {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.SonucBilgiHtml SonucField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.SonucBilgiHtml Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServisSonucOfSonucBilgiXmlYKHEH_S_P5", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class ServisSonucOfSonucBilgiXmlYKHEH_S_P5 : LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonuc {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.SonucBilgiXml SonucField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.SonucBilgiXml Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServisSonucOfSonucBilgiYKHEH_S_P5", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class ServisSonucOfSonucBilgiYKHEH_S_P5 : LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonuc {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.SonucBilgi SonucField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.SonucBilgi Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 : LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonuc {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.SinavGrupBilgi[] SonucField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.SinavGrupBilgi[] Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SonucKodu", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.CommonCont" +
        "racts")]
    public enum SonucKodu : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KayitBulunamadi = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Basarili = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GecersizVeri = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YetkisizIslem = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZamanAsimi = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeklenmeyenHata = 1000,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinavGrupBilgi", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.DataContra" +
        "cts.Sonuc")]
    [System.SerializableAttribute()]
    public partial class SinavGrupBilgi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinavSonucTemelBilgi", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.DataContra" +
        "cts.Sonuc")]
    [System.SerializableAttribute()]
    public partial class SinavSonucTemelBilgi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AciklamaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AciklamaTarihi {
            get {
                return this.AciklamaTarihiField;
            }
            set {
                if ((this.AciklamaTarihiField.Equals(value) != true)) {
                    this.AciklamaTarihiField = value;
                    this.RaisePropertyChanged("AciklamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SonucBilgiHtml", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.DataContra" +
        "cts.Sonuc")]
    [System.SerializableAttribute()]
    public partial class SonucBilgiHtml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AciklamaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SonucHtmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AciklamaTarihi {
            get {
                return this.AciklamaTarihiField;
            }
            set {
                if ((this.AciklamaTarihiField.Equals(value) != true)) {
                    this.AciklamaTarihiField = value;
                    this.RaisePropertyChanged("AciklamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SonucAd {
            get {
                return this.SonucAdField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucAdField, value) != true)) {
                    this.SonucAdField = value;
                    this.RaisePropertyChanged("SonucAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SonucHtml {
            get {
                return this.SonucHtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucHtmlField, value) != true)) {
                    this.SonucHtmlField = value;
                    this.RaisePropertyChanged("SonucHtml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SonucBilgiXml", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.DataContra" +
        "cts.Sonuc")]
    [System.SerializableAttribute()]
    public partial class SonucBilgiXml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AciklamaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AciklamaTarihi {
            get {
                return this.AciklamaTarihiField;
            }
            set {
                if ((this.AciklamaTarihiField.Equals(value) != true)) {
                    this.AciklamaTarihiField = value;
                    this.RaisePropertyChanged("AciklamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SonucAd {
            get {
                return this.SonucAdField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucAdField, value) != true)) {
                    this.SonucAdField = value;
                    this.RaisePropertyChanged("SonucAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xml {
            get {
                return this.XmlField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlField, value) != true)) {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SonucBilgi", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.DataContra" +
        "cts.Sonuc")]
    [System.SerializableAttribute()]
    public partial class SonucBilgi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AciklamaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisansUstuBasvuruSistemi.Ws_Osym_1.Puan[] PuanlarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucAciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucAdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AciklamaTarihi {
            get {
                return this.AciklamaTarihiField;
            }
            set {
                if ((this.AciklamaTarihiField.Equals(value) != true)) {
                    this.AciklamaTarihiField = value;
                    this.RaisePropertyChanged("AciklamaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisansUstuBasvuruSistemi.Ws_Osym_1.Puan[] Puanlar {
            get {
                return this.PuanlarField;
            }
            set {
                if ((object.ReferenceEquals(this.PuanlarField, value) != true)) {
                    this.PuanlarField = value;
                    this.RaisePropertyChanged("Puanlar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SonucAciklama {
            get {
                return this.SonucAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucAciklamaField, value) != true)) {
                    this.SonucAciklamaField = value;
                    this.RaisePropertyChanged("SonucAciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SonucAd {
            get {
                return this.SonucAdField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucAdField, value) != true)) {
                    this.SonucAdField = value;
                    this.RaisePropertyChanged("SonucAd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Puan", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.DataContra" +
        "cts.Sonuc")]
    [System.SerializableAttribute()]
    public partial class Puan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DegerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Deger {
            get {
                return this.DegerField;
            }
            set {
                if ((this.DegerField.Equals(value) != true)) {
                    this.DegerField = value;
                    this.RaisePropertyChanged("Deger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kod {
            get {
                return this.KodField;
            }
            set {
                if ((object.ReferenceEquals(this.KodField, value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.FaultContr" +
        "acts")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebugInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebugInfo {
            get {
                return this.DebugInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DebugInfoField, value) != true)) {
                    this.DebugInfoField = value;
                    this.RaisePropertyChanged("DebugInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ws_Osym_1.ISonuc")]
    public interface ISonuc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavGrupBilgileriniGetir", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServiceException), Action="http://tempuri.org/ISonuc/SinavGrupBilgileriniGetir", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.FaultContr" +
            "acts")]
        LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 SinavGrupBilgileriniGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavGrupBilgileriniGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5> SinavGrupBilgileriniGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavSonucHtml", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServiceException), Action="http://tempuri.org/ISonuc/SinavSonucHtml", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.FaultContr" +
            "acts")]
        LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 SinavSonucHtml(string adayTcKimlikNo, int sonucId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavSonucHtml", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5> SinavSonucHtmlAsync(string adayTcKimlikNo, int sonucId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavSonucXml", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServiceException), Action="http://tempuri.org/ISonuc/SinavSonucXml", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.FaultContr" +
            "acts")]
        LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiXmlYKHEH_S_P5 SinavSonucXml(string adayTcKimlikNo, int sonucId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavSonucXml", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiXmlYKHEH_S_P5> SinavSonucXmlAsync(string adayTcKimlikNo, int sonucId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavSonuclariGetir", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisansUstuBasvuruSistemi.Ws_Osym_1.ServiceException), Action="http://tempuri.org/ISonuc/SinavSonuclariGetir", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Osym.BilgiServisleri.Contracts.FaultContr" +
            "acts")]
        LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 SinavSonuclariGetir(string adayTcKimlikNo, int yil, int sinavGrupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISonuc/SinavSonuclariGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5> SinavSonuclariGetirAsync(string adayTcKimlikNo, int yil, int sinavGrupId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISonucChannel : LisansUstuBasvuruSistemi.Ws_Osym_1.ISonuc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SonucClient : System.ServiceModel.ClientBase<LisansUstuBasvuruSistemi.Ws_Osym_1.ISonuc>, LisansUstuBasvuruSistemi.Ws_Osym_1.ISonuc {
        
        public SonucClient() {
        }
        
        public SonucClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SonucClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SonucClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SonucClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5 SinavGrupBilgileriniGetir() {
            return base.Channel.SinavGrupBilgileriniGetir();
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavGrupBilgiYKHEH_S_P5> SinavGrupBilgileriniGetirAsync() {
            return base.Channel.SinavGrupBilgileriniGetirAsync();
        }
        
        public LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5 SinavSonucHtml(string adayTcKimlikNo, int sonucId) {
            return base.Channel.SinavSonucHtml(adayTcKimlikNo, sonucId);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiHtmlYKHEH_S_P5> SinavSonucHtmlAsync(string adayTcKimlikNo, int sonucId) {
            return base.Channel.SinavSonucHtmlAsync(adayTcKimlikNo, sonucId);
        }
        
        public LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiXmlYKHEH_S_P5 SinavSonucXml(string adayTcKimlikNo, int sonucId) {
            return base.Channel.SinavSonucXml(adayTcKimlikNo, sonucId);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfSonucBilgiXmlYKHEH_S_P5> SinavSonucXmlAsync(string adayTcKimlikNo, int sonucId) {
            return base.Channel.SinavSonucXmlAsync(adayTcKimlikNo, sonucId);
        }
        
        public LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5 SinavSonuclariGetir(string adayTcKimlikNo, int yil, int sinavGrupId) {
            return base.Channel.SinavSonuclariGetir(adayTcKimlikNo, yil, sinavGrupId);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_Osym_1.ServisSonucOfArrayOfSinavSonucTemelBilgiYKHEH_S_P5> SinavSonuclariGetirAsync(string adayTcKimlikNo, int yil, int sinavGrupId) {
            return base.Channel.SinavSonuclariGetirAsync(adayTcKimlikNo, yil, sinavGrupId);
        }
    }
}
