//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Ws_GsisOdeme {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsispaymentservice.net", ConfigurationName="Ws_GsisOdeme.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/paymentControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string paymentControl(string stdid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/paymentControl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> paymentControlAsync(string stdid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/getProgramFee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisansUstuBasvuruSistemi.Ws_GsisOdeme.FeeInfo getProgramFee(string programid, string edutypeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/getProgramFee", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_GsisOdeme.FeeInfo> getProgramFeeAsync(string programid, string edutypeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/getFirstPaymentDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getFirstPaymentDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/getFirstPaymentDate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getFirstPaymentDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/getLastPaymentDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getLastPaymentDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/getLastPaymentDate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getLastPaymentDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/setPaymentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setPaymentInfo(string stdid, string amount, string receiptno, string paymentdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsispaymentservice.net/setPaymentInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setPaymentInfoAsync(string stdid, string amount, string receiptno, string paymentdate);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gsispaymentservice.net")]
    public partial class FeeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amountField;
        
        private string firstpaymentdateField;
        
        private string lastpaymentdateField;
        
        private string returnInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstpaymentdate {
            get {
                return this.firstpaymentdateField;
            }
            set {
                this.firstpaymentdateField = value;
                this.RaisePropertyChanged("firstpaymentdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastpaymentdate {
            get {
                return this.lastpaymentdateField;
            }
            set {
                this.lastpaymentdateField = value;
                this.RaisePropertyChanged("lastpaymentdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string returnInfo {
            get {
                return this.returnInfoField;
            }
            set {
                this.returnInfoField = value;
                this.RaisePropertyChanged("returnInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : LisansUstuBasvuruSistemi.Ws_GsisOdeme.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<LisansUstuBasvuruSistemi.Ws_GsisOdeme.ServiceSoap>, LisansUstuBasvuruSistemi.Ws_GsisOdeme.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string paymentControl(string stdid) {
            return base.Channel.paymentControl(stdid);
        }
        
        public System.Threading.Tasks.Task<string> paymentControlAsync(string stdid) {
            return base.Channel.paymentControlAsync(stdid);
        }
        
        public LisansUstuBasvuruSistemi.Ws_GsisOdeme.FeeInfo getProgramFee(string programid, string edutypeid) {
            return base.Channel.getProgramFee(programid, edutypeid);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.Ws_GsisOdeme.FeeInfo> getProgramFeeAsync(string programid, string edutypeid) {
            return base.Channel.getProgramFeeAsync(programid, edutypeid);
        }
        
        public string getFirstPaymentDate() {
            return base.Channel.getFirstPaymentDate();
        }
        
        public System.Threading.Tasks.Task<string> getFirstPaymentDateAsync() {
            return base.Channel.getFirstPaymentDateAsync();
        }
        
        public string getLastPaymentDate() {
            return base.Channel.getLastPaymentDate();
        }
        
        public System.Threading.Tasks.Task<string> getLastPaymentDateAsync() {
            return base.Channel.getLastPaymentDateAsync();
        }
        
        public string setPaymentInfo(string stdid, string amount, string receiptno, string paymentdate) {
            return base.Channel.setPaymentInfo(stdid, amount, receiptno, paymentdate);
        }
        
        public System.Threading.Tasks.Task<string> setPaymentInfoAsync(string stdid, string amount, string receiptno, string paymentdate) {
            return base.Channel.setPaymentInfoAsync(stdid, amount, receiptno, paymentdate);
        }
    }
}
