//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Ws_GsisAktarim {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gsisregistrationservice.net", ConfigurationName="Ws_GsisAktarim.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/studentRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string studentRegistration(string xmlStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/studentRegistration", ReplyAction="*")]
        System.Threading.Tasks.Task<string> studentRegistrationAsync(string xmlStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/studentControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string studentControl(string tcKimlikNo, string eduTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/studentControl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> studentControlAsync(string tcKimlikNo, string eduTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/studentControlStdid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string studentControlStdid(string stdid, string eduTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/studentControlStdid", ReplyAction="*")]
        System.Threading.Tasks.Task<string> studentControlStdidAsync(string stdid, string eduTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/getBranchId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getBranchId(string tcKimlikNo, string eduTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gsisregistrationservice.net/getBranchId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getBranchIdAsync(string tcKimlikNo, string eduTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : LisansUstuBasvuruSistemi.Ws_GsisAktarim.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<LisansUstuBasvuruSistemi.Ws_GsisAktarim.ServiceSoap>, LisansUstuBasvuruSistemi.Ws_GsisAktarim.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string studentRegistration(string xmlStr) {
            return base.Channel.studentRegistration(xmlStr);
        }
        
        public System.Threading.Tasks.Task<string> studentRegistrationAsync(string xmlStr) {
            return base.Channel.studentRegistrationAsync(xmlStr);
        }
        
        public string studentControl(string tcKimlikNo, string eduTypeId) {
            return base.Channel.studentControl(tcKimlikNo, eduTypeId);
        }
        
        public System.Threading.Tasks.Task<string> studentControlAsync(string tcKimlikNo, string eduTypeId) {
            return base.Channel.studentControlAsync(tcKimlikNo, eduTypeId);
        }
        
        public string studentControlStdid(string stdid, string eduTypeId) {
            return base.Channel.studentControlStdid(stdid, eduTypeId);
        }
        
        public System.Threading.Tasks.Task<string> studentControlStdidAsync(string stdid, string eduTypeId) {
            return base.Channel.studentControlStdidAsync(stdid, eduTypeId);
        }
        
        public string getBranchId(string tcKimlikNo, string eduTypeId) {
            return base.Channel.getBranchId(tcKimlikNo, eduTypeId);
        }
        
        public System.Threading.Tasks.Task<string> getBranchIdAsync(string tcKimlikNo, string eduTypeId) {
            return base.Channel.getBranchIdAsync(tcKimlikNo, eduTypeId);
        }
    }
}
