//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.LdapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LdapService.SecureSoap")]
    public interface SecureSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        LisansUstuBasvuruSistemi.LdapService.LoginResponse Login(LisansUstuBasvuruSistemi.LdapService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.LdapService.LoginResponse> LoginAsync(LisansUstuBasvuruSistemi.LdapService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginSTD", ReplyAction="*")]
        LisansUstuBasvuruSistemi.LdapService.LoginSTDResponse LoginSTD(LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginSTD", ReplyAction="*")]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.LdapService.LoginSTDResponse> LoginSTDAsync(LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public LisansUstuBasvuruSistemi.LdapService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(LisansUstuBasvuruSistemi.LdapService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassKey;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserName, string Password, string PassKey) {
            this.UserName = UserName;
            this.Password = Password;
            this.PassKey = PassKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public LisansUstuBasvuruSistemi.LdapService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(LisansUstuBasvuruSistemi.LdapService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginSTDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginSTD", Namespace="http://tempuri.org/", Order=0)]
        public LisansUstuBasvuruSistemi.LdapService.LoginSTDRequestBody Body;
        
        public LoginSTDRequest() {
        }
        
        public LoginSTDRequest(LisansUstuBasvuruSistemi.LdapService.LoginSTDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginSTDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassKey;
        
        public LoginSTDRequestBody() {
        }
        
        public LoginSTDRequestBody(string UserName, string Password, string PassKey) {
            this.UserName = UserName;
            this.Password = Password;
            this.PassKey = PassKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginSTDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginSTDResponse", Namespace="http://tempuri.org/", Order=0)]
        public LisansUstuBasvuruSistemi.LdapService.LoginSTDResponseBody Body;
        
        public LoginSTDResponse() {
        }
        
        public LoginSTDResponse(LisansUstuBasvuruSistemi.LdapService.LoginSTDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginSTDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginSTDResult;
        
        public LoginSTDResponseBody() {
        }
        
        public LoginSTDResponseBody(bool LoginSTDResult) {
            this.LoginSTDResult = LoginSTDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecureSoapChannel : LisansUstuBasvuruSistemi.LdapService.SecureSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecureSoapClient : System.ServiceModel.ClientBase<LisansUstuBasvuruSistemi.LdapService.SecureSoap>, LisansUstuBasvuruSistemi.LdapService.SecureSoap {
        
        public SecureSoapClient() {
        }
        
        public SecureSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecureSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisansUstuBasvuruSistemi.LdapService.LoginResponse LisansUstuBasvuruSistemi.LdapService.SecureSoap.Login(LisansUstuBasvuruSistemi.LdapService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string UserName, string Password, string PassKey) {
            LisansUstuBasvuruSistemi.LdapService.LoginRequest inValue = new LisansUstuBasvuruSistemi.LdapService.LoginRequest();
            inValue.Body = new LisansUstuBasvuruSistemi.LdapService.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.PassKey = PassKey;
            LisansUstuBasvuruSistemi.LdapService.LoginResponse retVal = ((LisansUstuBasvuruSistemi.LdapService.SecureSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.LdapService.LoginResponse> LisansUstuBasvuruSistemi.LdapService.SecureSoap.LoginAsync(LisansUstuBasvuruSistemi.LdapService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.LdapService.LoginResponse> LoginAsync(string UserName, string Password, string PassKey) {
            LisansUstuBasvuruSistemi.LdapService.LoginRequest inValue = new LisansUstuBasvuruSistemi.LdapService.LoginRequest();
            inValue.Body = new LisansUstuBasvuruSistemi.LdapService.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.PassKey = PassKey;
            return ((LisansUstuBasvuruSistemi.LdapService.SecureSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisansUstuBasvuruSistemi.LdapService.LoginSTDResponse LisansUstuBasvuruSistemi.LdapService.SecureSoap.LoginSTD(LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest request) {
            return base.Channel.LoginSTD(request);
        }
        
        public bool LoginSTD(string UserName, string Password, string PassKey) {
            LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest inValue = new LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest();
            inValue.Body = new LisansUstuBasvuruSistemi.LdapService.LoginSTDRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.PassKey = PassKey;
            LisansUstuBasvuruSistemi.LdapService.LoginSTDResponse retVal = ((LisansUstuBasvuruSistemi.LdapService.SecureSoap)(this)).LoginSTD(inValue);
            return retVal.Body.LoginSTDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.LdapService.LoginSTDResponse> LisansUstuBasvuruSistemi.LdapService.SecureSoap.LoginSTDAsync(LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest request) {
            return base.Channel.LoginSTDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LisansUstuBasvuruSistemi.LdapService.LoginSTDResponse> LoginSTDAsync(string UserName, string Password, string PassKey) {
            LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest inValue = new LisansUstuBasvuruSistemi.LdapService.LoginSTDRequest();
            inValue.Body = new LisansUstuBasvuruSistemi.LdapService.LoginSTDRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            inValue.Body.PassKey = PassKey;
            return ((LisansUstuBasvuruSistemi.LdapService.SecureSoap)(this)).LoginSTDAsync(inValue);
        }
    }
}
