//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnabilimDaliYeterlikKomiteUyeleri
    {
        public int AnabilimdaliYeterlikKomiteUyeID { get; set; }
        public int AnabilimDaliID { get; set; }
        public int KullaniciID { get; set; }
        public int IslemYapanID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual AnabilimDallari AnabilimDallari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
