//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvurularYuklenenBelgeler
    {
        public int BasvurularYuklenenBelgeID { get; set; }
        public int BasvuruID { get; set; }
        public int BasvuruBelgeTipID { get; set; }
        public Nullable<int> SinavTipID { get; set; }
        public string BelgeAdi { get; set; }
        public string BelgeYolu { get; set; }
        public bool IsOnaylandi { get; set; }
        public Nullable<System.DateTime> OnaylamaTarihi { get; set; }
        public Nullable<int> OnaylamaYapanID { get; set; }
        public string OnaylamaYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual BasvuruBelgeTipleri BasvuruBelgeTipleri { get; set; }
        public virtual Basvurular Basvurular { get; set; }
    }
}
