//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecSinavTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasvuruSurecSinavTipleri()
        {
            this.BasvuruSurecSinavNotlaris = new HashSet<BasvuruSurecSinavNotlari>();
            this.BasvuruSurecSinavTarihleris = new HashSet<BasvuruSurecSinavTarihleri>();
            this.BasvuruSurecSinavTipleriDils = new HashSet<BasvuruSurecSinavTipleriDil>();
            this.BasvuruSurecSinavTipleriDonems = new HashSet<BasvuruSurecSinavTipleriDonem>();
            this.BasvuruSurecSinavTiplerSubSinavAraliks = new HashSet<BasvuruSurecSinavTiplerSubSinavAralik>();
        }
    
        public int BasvuruSurecSinavTipID { get; set; }
        public int BasvuruSurecID { get; set; }
        public int SinavTipID { get; set; }
        public string EnstituKod { get; set; }
        public int SinavTipGrupID { get; set; }
        public int SinavTipKod { get; set; }
        public bool WebService { get; set; }
        public string WebServiceKod { get; set; }
        public Nullable<int> WsSinavCekimTipID { get; set; }
        public bool OzelTarih { get; set; }
        public Nullable<int> OzelTarihTipID { get; set; }
        public Nullable<System.DateTime> Tarih1 { get; set; }
        public Nullable<System.DateTime> Tarih2 { get; set; }
        public Nullable<int> TarihGirisMaxGecmisYil { get; set; }
        public bool OzelNot { get; set; }
        public Nullable<int> OzelNotTipID { get; set; }
        public bool NotDonusum { get; set; }
        public string NotDonusumFormulu { get; set; }
        public bool KusuratVar { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public bool GIsTaahhutVar { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavNotlari> BasvuruSurecSinavNotlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTarihleri> BasvuruSurecSinavTarihleris { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OzelNotTipleri OzelNotTipleri { get; set; }
        public virtual OzelTarihTipleri OzelTarihTipleri { get; set; }
        public virtual SinavTipGruplari SinavTipGruplari { get; set; }
        public virtual SinavTipleri SinavTipleri { get; set; }
        public virtual WsSinavCekimTipleri WsSinavCekimTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriDil> BasvuruSurecSinavTipleriDils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriDonem> BasvuruSurecSinavTipleriDonems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTiplerSubSinavAralik> BasvuruSurecSinavTiplerSubSinavAraliks { get; set; }
    }
}
