//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecSinavTipleriOT_SNA_OT
    {
        public int BasvuruSurecSinavTipleriOT_SNA_OTID { get; set; }
        public int BasvuruSurecSinavTipleriOT_SNAID { get; set; }
        public int OgrenimTipKod { get; set; }
        public bool Ingilizce { get; set; }
        public bool IsGecerli { get; set; }
        public bool IsIstensin { get; set; }
        public bool IsOzelNotAralik { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
    
        public virtual BasvuruSurecSinavTipleriOT_SNA BasvuruSurecSinavTipleriOT_SNA { get; set; }
    }
}
