//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurecOtoMail
    {
        public int BasvuruSurecOtoMailID { get; set; }
        public int BasvuruSurecID { get; set; }
        public int ZamanTipID { get; set; }
        public int Zaman { get; set; }
        public bool Gonderildi { get; set; }
        public Nullable<int> GonderilenCount { get; set; }
        public string Gonderilenler { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual ZamanTipleri ZamanTipleri { get; set; }
    }
}
