//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruSurec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasvuruSurec()
        {
            this.Basvurulars = new HashSet<Basvurular>();
            this.BasvuruSurecBelgeTipleris = new HashSet<BasvuruSurecBelgeTipleri>();
            this.BasvuruSurecKotalars = new HashSet<BasvuruSurecKotalar>();
            this.BasvuruSurecMulakatSinavTurleris = new HashSet<BasvuruSurecMulakatSinavTurleri>();
            this.BasvuruSurecOgrenimTipleris = new HashSet<BasvuruSurecOgrenimTipleri>();
            this.BasvuruSurecOtoMails = new HashSet<BasvuruSurecOtoMail>();
            this.BasvuruSurecOTOrtBasvrs = new HashSet<BasvuruSurecOTOrtBasvr>();
            this.BasvuruSurecProgramlarAlandisiBolumKisitlamalaris = new HashSet<BasvuruSurecProgramlarAlandisiBolumKisitlamalari>();
            this.BasvuruSurecSinavTipleris = new HashSet<BasvuruSurecSinavTipleri>();
            this.BasvuruSurecSinavTipleriOT_SNA = new HashSet<BasvuruSurecSinavTipleriOT_SNA>();
            this.BasvuruSurecSinavTipleriOTNotAraliklaris = new HashSet<BasvuruSurecSinavTipleriOTNotAraliklari>();
            this.Mulakats = new HashSet<Mulakat>();
            this.MulakatSonuclaris = new HashSet<MulakatSonuclari>();
        }
    
        public int BasvuruSurecID { get; set; }
        public bool IsBasvuruOrYatayGecis { get; set; }
        public int BasvuruSurecTipID { get; set; }
        public string EnstituKod { get; set; }
        public int BaslangicYil { get; set; }
        public int BitisYil { get; set; }
        public int DonemID { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<System.DateTime> AGNOGirisBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> AGNOGirisBitisTarihi { get; set; }
        public Nullable<System.DateTime> SonucGirisBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> SonucGirisBitisTarihi { get; set; }
        public int Kota_BasvuruSurecKontrolTipID { get; set; }
        public int ToplamKota { get; set; }
        public bool isYuzdeGirisBolum { get; set; }
        public bool FarkliOgrenimTipleriAyniBasvurudaAlinabilsin { get; set; }
        public bool SinavYerBilgisiBolumMailiGonderildi { get; set; }
        public Nullable<System.DateTime> SinavYerBilgisiBolumMailiGonderimTarihi { get; set; }
        public bool SinavNotBilgisiBolumMailiGonderildi { get; set; }
        public Nullable<System.DateTime> SinavNotBilgisiBolumMailiGonderimTarihi { get; set; }
        public bool SinavYerBilgisiOgrenciMailiGonderildi { get; set; }
        public Nullable<System.DateTime> SinavYerBilgisiOgrenciMailiGonderimTarihi { get; set; }
        public bool SinavSonucBilgisiBolumMailiGonderildi { get; set; }
        public Nullable<System.DateTime> SinavSonucBilgisiBolumMailiGonderimTarihi { get; set; }
        public bool SinavSonucBilgisiOgrenciMailiGonderildi { get; set; }
        public Nullable<System.DateTime> SinavSonucBilgisiOgrenciMailiGonderimTarihi { get; set; }
        public bool KayitOlmayanOgrencilereAnketLinkiGonderildi { get; set; }
        public Nullable<System.DateTime> KayitOlmayanOgrencilereAnketLinkiGonderimTarihi { get; set; }
        public Nullable<int> AnketID { get; set; }
        public Nullable<int> KayitOlmayanlarAnketID { get; set; }
        public bool IsOgrenciSonucListesindePuanGozuksun { get; set; }
        public bool IsBelgeYuklemeVar { get; set; }
        public bool IsKayittaBelgeOnayiZorunlu { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Anket Anket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
        public virtual BasvuruSurecKontrolTipleri BasvuruSurecKontrolTipleri { get; set; }
        public virtual BasvuruSurecTipleri BasvuruSurecTipleri { get; set; }
        public virtual Donemler Donemler { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecBelgeTipleri> BasvuruSurecBelgeTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecKotalar> BasvuruSurecKotalars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecMulakatSinavTurleri> BasvuruSurecMulakatSinavTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecOgrenimTipleri> BasvuruSurecOgrenimTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecOtoMail> BasvuruSurecOtoMails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecOTOrtBasvr> BasvuruSurecOTOrtBasvrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecProgramlarAlandisiBolumKisitlamalari> BasvuruSurecProgramlarAlandisiBolumKisitlamalaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleri> BasvuruSurecSinavTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOT_SNA> BasvuruSurecSinavTipleriOT_SNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOTNotAraliklari> BasvuruSurecSinavTipleriOTNotAraliklaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mulakat> Mulakats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatSonuclari> MulakatSonuclaris { get; set; }
    }
}
