//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruBelgeTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasvuruBelgeTipleri()
        {
            this.BasvuruBelgeTipleriYuklemeSeklis = new HashSet<BasvuruBelgeTipleriYuklemeSekli>();
            this.BasvurularYuklenenBelgelers = new HashSet<BasvurularYuklenenBelgeler>();
            this.BasvuruSurecBelgeTipleris = new HashSet<BasvuruSurecBelgeTipleri>();
            this.BasvuruSurecBelgeTipleriYuklemeSeklis = new HashSet<BasvuruSurecBelgeTipleriYuklemeSekli>();
        }
    
        public int BasvuruBelgeTipID { get; set; }
        public string BasvuruBelgeTipAdi { get; set; }
        public bool IsZorunlu { get; set; }
        public Nullable<bool> IsYerliOrYabanci { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruBelgeTipleriYuklemeSekli> BasvuruBelgeTipleriYuklemeSeklis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularYuklenenBelgeler> BasvurularYuklenenBelgelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecBelgeTipleri> BasvuruSurecBelgeTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecBelgeTipleriYuklemeSekli> BasvuruSurecBelgeTipleriYuklemeSeklis { get; set; }
    }
}
