//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvurularTercihleriKayitOdemeleri
    {
        public int BasvuruTercihKayitOdemeID { get; set; }
        public int BasvuruTercihID { get; set; }
        public bool IsDekontGirisOrSanalPos { get; set; }
        public int DonemNo { get; set; }
        public string DekontNo { get; set; }
        public Nullable<double> Ucret { get; set; }
        public Nullable<System.DateTime> DekontTarih { get; set; }
        public bool IsOdendi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual BasvurularTercihleri BasvurularTercihleri { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
