//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BelgeTipDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BelgeTipDetay()
        {
            this.BelgeTipDetayBelgelers = new HashSet<BelgeTipDetayBelgeler>();
            this.BelgeTipDetaySaatlers = new HashSet<BelgeTipDetaySaatler>();
        }
    
        public int BelgeTipDetayID { get; set; }
        public string EnstituKod { get; set; }
        public int OgrenimDurumID { get; set; }
        public bool UcretAlimiVar { get; set; }
        public Nullable<double> BelgeFiyati { get; set; }
        public Nullable<int> UcretsizMiktar { get; set; }
        public Nullable<int> DonemlikKota { get; set; }
        public string UcretAciklamasiLink { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OgrenimDurumlari OgrenimDurumlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTipDetayBelgeler> BelgeTipDetayBelgelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTipDetaySaatler> BelgeTipDetaySaatlers { get; set; }
    }
}
