//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BelgeTalepleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BelgeTalepleri()
        {
            this.AnketCevaplaris = new HashSet<AnketCevaplari>();
        }
    
        public int BelgeTalepID { get; set; }
        public string EnstituKod { get; set; }
        public System.DateTime TalepTarihi { get; set; }
        public int BelgeDurumID { get; set; }
        public string BelgeDurumAciklamasi { get; set; }
        public int BelgeTipID { get; set; }
        public int OgrenimDurumID { get; set; }
        public string BelgeDilKodu { get; set; }
        public int OgrenimTipKod { get; set; }
        public int OgretimYiliBaslangic { get; set; }
        public int OgretimYiliBitis { get; set; }
        public int DonemID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string AdiSoyadi { get; set; }
        public string OgrenciNo { get; set; }
        public string ErisimKodu { get; set; }
        public string ProgramKod { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public int IstenenBelgeSayisi { get; set; }
        public string BelgeAdi { get; set; }
        public string BelgeAciklamasi { get; set; }
        public bool UcretAlimiVar { get; set; }
        public Nullable<double> BelgeFiyati { get; set; }
        public Nullable<int> UcretsizMiktar { get; set; }
        public Nullable<int> DonemlikKota { get; set; }
        public string UcretAciklamasiLink { get; set; }
        public Nullable<int> VerilenBelgeSayisi { get; set; }
        public Nullable<double> VerilenBelgeTutar { get; set; }
        public int EklenecekGun { get; set; }
        public Nullable<System.TimeSpan> TeslimBaslangicSaat { get; set; }
        public Nullable<System.TimeSpan> TeslimBitisSaat { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplari> AnketCevaplaris { get; set; }
        public virtual BelgeDurumlari BelgeDurumlari { get; set; }
        public virtual BelgeTipleri BelgeTipleri { get; set; }
        public virtual Donemler Donemler { get; set; }
        public virtual Enstituler Enstituler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OgrenimDurumlari OgrenimDurumlari { get; set; }
        public virtual Programlar Programlar { get; set; }
    }
}
