//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnstituKayitKriterBKOT
    {
        public int EnstituKayitKriterBOTID { get; set; }
        public string EnstituKod { get; set; }
        public int OgrenimTipID { get; set; }
        public int OgrenimTipID2 { get; set; }
    
        public virtual Enstituler Enstituler { get; set; }
    }
}
