//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciLisansBilgileri
    {
        public int KullaniciLisansID { get; set; }
        public int KullaniciID { get; set; }
        public int LisansTipID { get; set; }
        public int UniversiteID { get; set; }
        public string FakulteAdi { get; set; }
        public int OgrenciBolumID { get; set; }
        public System.DateTime BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> MezuniyetTarihi { get; set; }
        public int NotSistemID { get; set; }
        public double MezuniyetNotu { get; set; }
    }
}
