//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullaniciTipleri()
        {
            this.Basvurulars = new HashSet<Basvurular>();
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.MezuniyetBasvurularis = new HashSet<MezuniyetBasvurulari>();
            this.ProgramKullaniciTipleris = new HashSet<ProgramKullaniciTipleri>();
            this.Programlars = new HashSet<Programlar>();
            this.SRTalepTipKullanicilars = new HashSet<SRTalepTipKullanicilar>();
            this.TDOBasvurus = new HashSet<TDOBasvuru>();
            this.TIBasvurus = new HashSet<TIBasvuru>();
        }
    
        public int KullaniciTipID { get; set; }
        public bool KurumIci { get; set; }
        public bool Yerli { get; set; }
        public bool YeniHesapOlusturabilir { get; set; }
        public bool BasvuruYapabilir { get; set; }
        public string KullaniciTipAdi { get; set; }
        public bool IsAktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulari> MezuniyetBasvurularis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramKullaniciTipleri> ProgramKullaniciTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programlar> Programlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepTipKullanicilar> SRTalepTipKullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuru> TDOBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuru> TIBasvurus { get; set; }
    }
}
