//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedeniHaller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedeniHaller()
        {
            this.Basvurulars = new HashSet<Basvurular>();
        }
    
        public int MedeniHalID { get; set; }
        public string MedeniHalAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
    }
}
