//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetJuriOneriFormlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetJuriOneriFormlari()
        {
            this.MezuniyetJuriOneriFormuJurileris = new HashSet<MezuniyetJuriOneriFormuJurileri>();
        }
    
        public int MezuniyetJuriOneriFormID { get; set; }
        public int MezuniyetBasvurulariID { get; set; }
        public string UniqueID { get; set; }
        public Nullable<bool> IsTezBasligiDegisti { get; set; }
        public string YeniTezBaslikTr { get; set; }
        public string YeniTezBaslikEn { get; set; }
        public Nullable<bool> EYKYaGonderildi { get; set; }
        public Nullable<int> EYKYaGonderildiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaGonderildiIslemTarihi { get; set; }
        public Nullable<bool> EYKDaOnaylandi { get; set; }
        public Nullable<int> EYKDaOnaylandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKDaOnaylandiOnayTarihi { get; set; }
        public string EYKDaOnaylanmadiDurumAciklamasi { get; set; }
        public Nullable<bool> IsTezSanayiVeIsBirligiKapsamindaGerceklesti { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual MezuniyetBasvurulari MezuniyetBasvurulari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetJuriOneriFormuJurileri> MezuniyetJuriOneriFormuJurileris { get; set; }
    }
}
