//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciYonetmelikleriOT
    {
        public int MezuniyetSureciYonetmelikleriOTID { get; set; }
        public int MezuniyetSureciYonetmelikID { get; set; }
        public int OgrenimTipKod { get; set; }
        public int MezuniyetYayinTurID { get; set; }
        public bool IsGecerli { get; set; }
        public bool IsZorunlu { get; set; }
        public string GrupKodu { get; set; }
    
        public virtual MezuniyetSureciYonetmelikleri MezuniyetSureciYonetmelikleri { get; set; }
        public virtual MezuniyetYayinTurleri MezuniyetYayinTurleri { get; set; }
    }
}
