//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetJuriOneriFormuJurileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetJuriOneriFormuJurileri()
        {
            this.SRTaleplerJuris = new HashSet<SRTaleplerJuri>();
        }
    
        public int MezuniyetJuriOneriFormuJuriID { get; set; }
        public int MezuniyetJuriOneriFormID { get; set; }
        public string JuriTipAdi { get; set; }
        public string UnvanAdi { get; set; }
        public string AdSoyad { get; set; }
        public string EMail { get; set; }
        public string UniversiteAdi { get; set; }
        public string AnabilimdaliProgramAdi { get; set; }
        public string UzmanlikAlani { get; set; }
        public Nullable<bool> IsAsilOrYedek { get; set; }
    
        public virtual MezuniyetJuriOneriFormlari MezuniyetJuriOneriFormlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTaleplerJuri> SRTaleplerJuris { get; set; }
    }
}
