//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciYayinTurleri
    {
        public int MezuniyetSureciYayinTurID { get; set; }
        public int MezuniyetSurecID { get; set; }
        public bool TarihIstensin { get; set; }
        public int MezuniyetYayinTurID { get; set; }
        public Nullable<int> MezuniyetYayinBelgeTurID { get; set; }
        public bool BelgeZorunlu { get; set; }
        public Nullable<int> KaynakMezuniyetYayinLinkTurID { get; set; }
        public bool KaynakLinkiZorunlu { get; set; }
        public Nullable<int> MezuniyetYayinMetinTurID { get; set; }
        public bool MetinZorunlu { get; set; }
        public Nullable<int> YayinMezuniyetYayinLinkTurID { get; set; }
        public bool YayinLinkiZorunlu { get; set; }
        public bool YayinIndexTurIstensin { get; set; }
        public Nullable<int> MezuniyetYayinIndexTurID { get; set; }
        public bool YayinKabulEdilmisMakaleIstensin { get; set; }
        public bool YayinYazarlarIstensin { get; set; }
        public bool YayinDergiAdiIstensin { get; set; }
        public bool YayinYilCiltSayiIstensin { get; set; }
        public bool YayinProjeTurIstensin { get; set; }
        public bool YayinProjeEkibiIstensin { get; set; }
        public bool YayinMevcutDurumIstensin { get; set; }
        public bool YayinDeatKurulusIstensin { get; set; }
        public bool IsTarihAraligiIstensin { get; set; }
        public bool YayinEtkinlikAdiIstensin { get; set; }
        public bool YayinYerBilgisiIstensin { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    }
}
