//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciOtoMailTezTeslim
    {
        public int MezuniyetSurecOtoMailTezTeslimID { get; set; }
        public int MezuniyetSurecOtoMailID { get; set; }
        public int MezuniyetBasvurulariID { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
