//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSureciOgrenimTipKriterleri
    {
        public int MezuniyetSureciOgrenimTipKriterID { get; set; }
        public int MezuniyetSurecID { get; set; }
        public int OgrenimTipID { get; set; }
        public int OgrenimTipKod { get; set; }
        public string MBasvuruSonDonemKaydiKontrolEdilecekDersKodlari { get; set; }
        public string MBasvuruEtikNotKriteri { get; set; }
        public string MBasvuruSeminerNotKriteri { get; set; }
        public int MBasvuruToplamKrediKriteri { get; set; }
        public double MBasvuruAGNOKriteri { get; set; }
        public int MBasvuruAKTSKriteri { get; set; }
        public int MBSinavUzatmaSuresiGun { get; set; }
        public int MBTezTeslimSuresiGun { get; set; }
        public int MBSRTalebiKacGunSonraAlabilir { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual MezuniyetSureci MezuniyetSureci { get; set; }
        public virtual OgrenimTipleri OgrenimTipleri { get; set; }
    }
}
