//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetBasvurulari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MezuniyetBasvurulari()
        {
            this.AnketCevaplaris = new HashSet<AnketCevaplari>();
            this.MezuniyetBasvurulariTezDosyalaris = new HashSet<MezuniyetBasvurulariTezDosyalari>();
            this.MezuniyetBasvurulariTezTeslimFormlaris = new HashSet<MezuniyetBasvurulariTezTeslimFormlari>();
            this.MezuniyetBasvurulariYayins = new HashSet<MezuniyetBasvurulariYayin>();
            this.MezuniyetJuriOneriFormlaris = new HashSet<MezuniyetJuriOneriFormlari>();
            this.SRTalepleris = new HashSet<SRTalepleri>();
        }
    
        public int MezuniyetBasvurulariID { get; set; }
        public System.Guid RowID { get; set; }
        public int MezuniyetSurecID { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int MezuniyetYayinKontrolDurumID { get; set; }
        public string MezuniyetYayinKontrolDurumAciklamasi { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<int> KullaniciTipID { get; set; }
        public string ResimAdi { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> UyrukKod { get; set; }
        public string TcKimlikNo { get; set; }
        public string OgrenciNo { get; set; }
        public int OgrenimDurumID { get; set; }
        public int OgrenimTipKod { get; set; }
        public string ProgramKod { get; set; }
        public Nullable<int> KayitOgretimYiliBaslangic { get; set; }
        public Nullable<int> KayitOgretimYiliDonemID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<bool> IsTezDiliTr { get; set; }
        public string TezBaslikTr { get; set; }
        public string TezBaslikEn { get; set; }
        public Nullable<int> TezDanismanID { get; set; }
        public Nullable<bool> IsDanismanOnay { get; set; }
        public Nullable<System.DateTime> DanismanOnayTarihi { get; set; }
        public string DanismanOnayAciklama { get; set; }
        public string TezTeslimFormKodu { get; set; }
        public Nullable<System.Guid> TezTeslimUniqueID { get; set; }
        public string TezDanismanUnvani { get; set; }
        public string TezDanismanAdi { get; set; }
        public string TezEsDanismanUnvani { get; set; }
        public string TezEsDanismanAdi { get; set; }
        public string TezEsDanismanEMail { get; set; }
        public string TezOzet { get; set; }
        public string OzetAnahtarKelimeler { get; set; }
        public string TezOzetHtml { get; set; }
        public string TezAbstract { get; set; }
        public string AbstractAnahtarKelimeler { get; set; }
        public string TezAbstractHtml { get; set; }
        public string DanismanImzaliFormDosyaAdi { get; set; }
        public string DanismanImzaliFormDosyaYolu { get; set; }
        public Nullable<int> MezuniyetSinavDurumID { get; set; }
        public Nullable<System.DateTime> MezuniyetSinavDurumIslemTarihi { get; set; }
        public Nullable<int> MezuniyetSinavDurumIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKTarihi { get; set; }
        public Nullable<System.DateTime> TezTeslimSonTarih { get; set; }
        public Nullable<bool> IsMezunOldu { get; set; }
        public Nullable<System.DateTime> MezuniyetTarihi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnketCevaplari> AnketCevaplaris { get; set; }
        public virtual Donemler Donemler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual KullaniciTipleri KullaniciTipleri { get; set; }
        public virtual MezuniyetSureci MezuniyetSureci { get; set; }
        public virtual MezuniyetYayinKontrolDurumlari MezuniyetYayinKontrolDurumlari { get; set; }
        public virtual OgrenimDurumlari OgrenimDurumlari { get; set; }
        public virtual Programlar Programlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulariTezDosyalari> MezuniyetBasvurulariTezDosyalaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulariTezTeslimFormlari> MezuniyetBasvurulariTezTeslimFormlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulariYayin> MezuniyetBasvurulariYayins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetJuriOneriFormlari> MezuniyetJuriOneriFormlaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTalepleri> SRTalepleris { get; set; }
    }
}
