//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezuniyetSurecOtoMail
    {
        public int MezuniyetSurecOtoMailID { get; set; }
        public int MezuniyetSurecID { get; set; }
        public Nullable<int> MailSablonTipID { get; set; }
        public int ZamanTipID { get; set; }
        public int Zaman { get; set; }
        public bool Gonderildi { get; set; }
        public Nullable<int> GonderilenCount { get; set; }
        public string Gonderilenler { get; set; }
        public string GonderilenMBID { get; set; }
    
        public virtual MezuniyetSureci MezuniyetSureci { get; set; }
    }
}
