//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MulakatSonuclari
    {
        public int MulakatSonucID { get; set; }
        public int MulakatSonucTipID { get; set; }
        public Nullable<int> KayitDurumID { get; set; }
        public int BasvuruSurecID { get; set; }
        public Nullable<int> MulakatID { get; set; }
        public int BasvuruID { get; set; }
        public int BasvuruTercihID { get; set; }
        public int AlanTipID { get; set; }
        public Nullable<bool> BilimselHazirlikVar { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<double> AlesNotuOrDosyaNotu { get; set; }
        public Nullable<double> Agno { get; set; }
        public Nullable<bool> SinavaGirmediY { get; set; }
        public Nullable<double> YaziliNotu { get; set; }
        public Nullable<bool> SinavaGirmediS { get; set; }
        public Nullable<double> SozluNotu { get; set; }
        public Nullable<double> GirisSinavNotu { get; set; }
        public Nullable<double> GenelBasariNotu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual AlanTipleri AlanTipleri { get; set; }
        public virtual Basvurular Basvurular { get; set; }
        public virtual BasvurularTercihleri BasvurularTercihleri { get; set; }
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual KayitDurumlari KayitDurumlari { get; set; }
        public virtual Mulakat Mulakat { get; set; }
        public virtual MulakatSonucTipleri MulakatSonucTipleri { get; set; }
    }
}
