//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MulakatJuri
    {
        public int MulakatJuriID { get; set; }
        public int MulakatID { get; set; }
        public bool IsAsil { get; set; }
        public int SiraNo { get; set; }
        public string JuriAdi { get; set; }
    
        public virtual Mulakat Mulakat { get; set; }
    }
}
