//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mulakat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mulakat()
        {
            this.MulakatDetays = new HashSet<MulakatDetay>();
            this.MulakatJuris = new HashSet<MulakatJuri>();
            this.MulakatSonuclaris = new HashSet<MulakatSonuclari>();
        }
    
        public int MulakatID { get; set; }
        public int BasvuruSurecID { get; set; }
        public string ProgramKod { get; set; }
        public int OgrenimTipKod { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIp { get; set; }
    
        public virtual BasvuruSurec BasvuruSurec { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Programlar Programlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatDetay> MulakatDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatJuri> MulakatJuris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatSonuclari> MulakatSonuclaris { get; set; }
    }
}
