//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciBolumleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgrenciBolumleri()
        {
            this.BasvuruSurecProgramlarAlandisiBolumKisitlamalaris = new HashSet<BasvuruSurecProgramlarAlandisiBolumKisitlamalari>();
            this.BolumEslestirs = new HashSet<BolumEslestir>();
            this.ProgramlarAlandisiBolumKisitlamalaris = new HashSet<ProgramlarAlandisiBolumKisitlamalari>();
        }
    
        public int OgrenciBolumID { get; set; }
        public string EnstituKod { get; set; }
        public string BolumAdi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecProgramlarAlandisiBolumKisitlamalari> BasvuruSurecProgramlarAlandisiBolumKisitlamalaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolumEslestir> BolumEslestirs { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OgrenciBolumleri OgrenciBolumleri1 { get; set; }
        public virtual OgrenciBolumleri OgrenciBolumleri2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramlarAlandisiBolumKisitlamalari> ProgramlarAlandisiBolumKisitlamalaris { get; set; }
    }
}
