//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenimTipleriOrtBasvr
    {
        public int OgrenimTipleriOrtBasvrID { get; set; }
        public string EnstituKod { get; set; }
        public int OgrenimTipKod { get; set; }
        public int OgrenimTipKod2 { get; set; }
    }
}
