//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programlar()
        {
            this.BasvurularTercihleris = new HashSet<BasvurularTercihleri>();
            this.BasvuruSurecKotalars = new HashSet<BasvuruSurecKotalar>();
            this.BasvuruSurecProgramlarAlandisiBolumKisitlamalaris = new HashSet<BasvuruSurecProgramlarAlandisiBolumKisitlamalari>();
            this.BasvuruSurecSinavTipleriOT_SNA_PR = new HashSet<BasvuruSurecSinavTipleriOT_SNA_PR>();
            this.BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlars = new HashSet<BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlar>();
            this.BelgeTalepleris = new HashSet<BelgeTalepleri>();
            this.BolumEslestirs = new HashSet<BolumEslestir>();
            this.Kotalars = new HashSet<Kotalar>();
            this.Kullanicilars = new HashSet<Kullanicilar>();
            this.KullaniciProgramlaris = new HashSet<KullaniciProgramlari>();
            this.MezuniyetBasvurularis = new HashSet<MezuniyetBasvurulari>();
            this.Mulakats = new HashSet<Mulakat>();
            this.ProgramKullaniciTipleris = new HashSet<ProgramKullaniciTipleri>();
            this.ProgramlarAlandisiBolumKisitlamalaris = new HashSet<ProgramlarAlandisiBolumKisitlamalari>();
            this.ProgramlarAlesEslesmeleris = new HashSet<ProgramlarAlesEslesmeleri>();
            this.SinavTipleriOT_SNA_PR = new HashSet<SinavTipleriOT_SNA_PR>();
            this.SinavTipleriOTNotAraliklariGecersizProgramlars = new HashSet<SinavTipleriOTNotAraliklariGecersizProgramlar>();
            this.TDOBasvurus = new HashSet<TDOBasvuru>();
            this.TDOBasvuruDanismen = new HashSet<TDOBasvuruDanisman>();
            this.TIBasvurus = new HashSet<TIBasvuru>();
        }
    
        public string ProgramKod { get; set; }
        public int AnabilimDaliID { get; set; }
        public string AnabilimDaliKod { get; set; }
        public int AlesTipID { get; set; }
        public bool Ingilizce { get; set; }
        public int KullaniciTipID { get; set; }
        public bool Ucretli { get; set; }
        public Nullable<double> Ucret { get; set; }
        public bool ProgramSecimiEkBilgi { get; set; }
        public bool AlesNotuYuksekOlanAlinsin { get; set; }
        public bool LYLHerhangiBirindeGecenAlanIci { get; set; }
        public Nullable<int> BasvuruAgnoAlimTipID { get; set; }
        public Nullable<int> LYuzdeOran { get; set; }
        public Nullable<int> YLYuzdeOran { get; set; }
        public Nullable<double> YLAgnoKriteri { get; set; }
        public Nullable<double> TYLAgnoKriteri { get; set; }
        public Nullable<double> DAgnoKriteri { get; set; }
        public Nullable<double> BDAgnoKriteri { get; set; }
        public bool IsAlandisiBolumKisitlamasi { get; set; }
        public bool YokOgrenciKontroluYap { get; set; }
        public string ProgramAdi { get; set; }
        public string Aciklama { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual AlesTipleri AlesTipleri { get; set; }
        public virtual AnabilimDallari AnabilimDallari { get; set; }
        public virtual BasvuruAgnoAlimTipleri BasvuruAgnoAlimTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvurularTercihleri> BasvurularTercihleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecKotalar> BasvuruSurecKotalars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecProgramlarAlandisiBolumKisitlamalari> BasvuruSurecProgramlarAlandisiBolumKisitlamalaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOT_SNA_PR> BasvuruSurecSinavTipleriOT_SNA_PR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlar> BasvuruSurecSinavTipleriOTNotAraliklariGecersizProgramlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BelgeTalepleri> BelgeTalepleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BolumEslestir> BolumEslestirs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kotalar> Kotalars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilars { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciProgramlari> KullaniciProgramlaris { get; set; }
        public virtual KullaniciTipleri KullaniciTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MezuniyetBasvurulari> MezuniyetBasvurularis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mulakat> Mulakats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramKullaniciTipleri> ProgramKullaniciTipleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramlarAlandisiBolumKisitlamalari> ProgramlarAlandisiBolumKisitlamalaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramlarAlesEslesmeleri> ProgramlarAlesEslesmeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleriOT_SNA_PR> SinavTipleriOT_SNA_PR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleriOTNotAraliklariGecersizProgramlar> SinavTipleriOTNotAraliklariGecersizProgramlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuru> TDOBasvurus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDOBasvuruDanisman> TDOBasvuruDanismen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIBasvuru> TIBasvurus { get; set; }
    }
}
