//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramlarEkBilgi
    {
        public int ProgramlarEkBilgiID { get; set; }
        public string ProgramKod { get; set; }
        public string DilKodu { get; set; }
        public string Aciklama { get; set; }
        public string AciklamaHtml { get; set; }
    }
}
