//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavTipleriDonem
    {
        public int SinavTipDonemID { get; set; }
        public int SinavTipID { get; set; }
        public Nullable<int> SinavDilID { get; set; }
        public int Yil { get; set; }
        public string WsDonemKod { get; set; }
        public string WsDonemAd { get; set; }
        public bool IsTaahhutVar { get; set; }
    
        public virtual SinavDilleri SinavDilleri { get; set; }
        public virtual SinavTipleri SinavTipleri { get; set; }
    }
}
