//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinavTipleriOTNotAraliklari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinavTipleriOTNotAraliklari()
        {
            this.SinavTipleriOTNotAraliklariGecersizProgramlars = new HashSet<SinavTipleriOTNotAraliklariGecersizProgramlar>();
        }
    
        public int SinavTipleriOTNotAralikID { get; set; }
        public string EnstituKod { get; set; }
        public int SinavTipID { get; set; }
        public int OgrenimTipKod { get; set; }
        public bool Ingilizce { get; set; }
        public bool IsGecerli { get; set; }
        public bool IsIstensin { get; set; }
        public bool IsOzelNotAralik { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
    
        public virtual Enstituler Enstituler { get; set; }
        public virtual SinavTipleri SinavTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinavTipleriOTNotAraliklariGecersizProgramlar> SinavTipleriOTNotAraliklariGecersizProgramlars { get; set; }
    }
}
