//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SROzelTanimGunler
    {
        public int SROzelTanimGunID { get; set; }
        public int SROzelTanimID { get; set; }
        public int HaftaGunID { get; set; }
    
        public virtual HaftaGunleri HaftaGunleri { get; set; }
        public virtual SROzelTanimlar SROzelTanimlar { get; set; }
    }
}
