//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SROzelTanimlar
    {
        public int SROzelTanimID { get; set; }
        public int SROzelTanimTipID { get; set; }
        public Nullable<int> SRTalepTipID { get; set; }
        public Nullable<int> SRSalonID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Ay { get; set; }
        public Nullable<int> Gun { get; set; }
        public Nullable<System.DateTime> BasTarih { get; set; }
        public Nullable<System.DateTime> BitTarih { get; set; }
        public string Aciklama { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual SROzelTanimTipleri SROzelTanimTipleri { get; set; }
        public virtual SRTalepTipleri SRTalepTipleri { get; set; }
    }
}
