//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRSaatler
    {
        public int SRSaatID { get; set; }
        public int SRSalonID { get; set; }
        public int HaftaGunID { get; set; }
        public System.TimeSpan BasSaat { get; set; }
        public System.TimeSpan BitSaat { get; set; }
    
        public virtual HaftaGunleri HaftaGunleri { get; set; }
        public virtual SRSalonlar SRSalonlar { get; set; }
    }
}
