//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRTaleplerJuri
    {
        public int SRTalepJuriID { get; set; }
        public System.Guid UniqueID { get; set; }
        public int SRTalepID { get; set; }
        public Nullable<int> MezuniyetJuriOneriFormuJuriID { get; set; }
        public string UniversiteAdi { get; set; }
        public string AnabilimdaliProgramAdi { get; set; }
        public string JuriTipAdi { get; set; }
        public string UnvanAdi { get; set; }
        public string JuriAdi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsLinkGonderildi { get; set; }
        public Nullable<System.DateTime> LinkGonderimTarihi { get; set; }
        public Nullable<int> LinkGonderenID { get; set; }
        public Nullable<int> MezuniyetSinavDurumID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> DegerlendirmeYapanID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeIslemTarihi { get; set; }
        public string DegerlendirmeIslemYapanIP { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual MezuniyetJuriOneriFormuJurileri MezuniyetJuriOneriFormuJurileri { get; set; }
        public virtual MezuniyetSinavDurumlari MezuniyetSinavDurumlari { get; set; }
        public virtual SRTalepleri SRTalepleri { get; set; }
    }
}
