//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRTalepleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRTalepleri()
        {
            this.SRTaleplerJuris = new HashSet<SRTaleplerJuri>();
        }
    
        public int SRTalepID { get; set; }
        public Nullable<System.Guid> UniqueID { get; set; }
        public string EnstituKod { get; set; }
        public Nullable<int> TIBasvuruAraRaporID { get; set; }
        public Nullable<int> MezuniyetBasvurulariID { get; set; }
        public Nullable<int> ToBasvuruSavunmaID { get; set; }
        public bool IsOnline { get; set; }
        public int SRTalepTipID { get; set; }
        public int TalepYapanID { get; set; }
        public Nullable<int> SRSalonID { get; set; }
        public string SalonAdi { get; set; }
        public System.DateTime Tarih { get; set; }
        public int HaftaGunID { get; set; }
        public System.TimeSpan BasSaat { get; set; }
        public System.TimeSpan BitSaat { get; set; }
        public string TezOzeti { get; set; }
        public string TezOzetiHtml { get; set; }
        public string DanismanAdi { get; set; }
        public string EsDanismanAdi { get; set; }
        public Nullable<bool> IsYokDrBursiyeriVar { get; set; }
        public string YokDrOncelikliAlan { get; set; }
        public Nullable<bool> IsTezBasligiDegisti { get; set; }
        public string YeniTezBaslikTr { get; set; }
        public string YeniTezBaslikEn { get; set; }
        public string Aciklama { get; set; }
        public int SRDurumID { get; set; }
        public string SRDurumAciklamasi { get; set; }
        public Nullable<System.DateTime> RSBaslatildiMailGonderimTarihi { get; set; }
        public Nullable<bool> IsOyBirligiOrCoklugu { get; set; }
        public Nullable<int> JuriSonucMezuniyetSinavDurumID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeSonucMailTarihi { get; set; }
        public Nullable<int> MezuniyetSinavDurumID { get; set; }
        public Nullable<System.DateTime> MezuniyetSinavDurumIslemTarihi { get; set; }
        public Nullable<int> MezuniyetSinavDurumIslemYapanID { get; set; }
        public Nullable<bool> IsOgrenciUzatmaSonrasiOnay { get; set; }
        public Nullable<System.DateTime> OgrenciOnayTarihi { get; set; }
        public Nullable<bool> IsDanismanUzatmaSonrasiOnay { get; set; }
        public Nullable<System.DateTime> DanismanOnayTarihi { get; set; }
        public string DanismanUzatmaSonrasiOnayAciklama { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Enstituler Enstituler { get; set; }
        public virtual HaftaGunleri HaftaGunleri { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual MezuniyetBasvurulari MezuniyetBasvurulari { get; set; }
        public virtual MezuniyetSinavDurumlari MezuniyetSinavDurumlari { get; set; }
        public virtual SRDurumlari SRDurumlari { get; set; }
        public virtual SRSalonlar SRSalonlar { get; set; }
        public virtual SRTalepTipleri SRTalepTipleri { get; set; }
        public virtual TIBasvuruAraRapor TIBasvuruAraRapor { get; set; }
        public virtual ToBasvuruSavunma ToBasvuruSavunma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRTaleplerJuri> SRTaleplerJuris { get; set; }
    }
}
