//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRTalepleriBezCiltFormu
    {
        public int SRTalepleriBezCiltFormID { get; set; }
        public System.Guid RowID { get; set; }
        public int SRTalepID { get; set; }
        public bool IsTezDiliTr { get; set; }
        public string TezDili { get; set; }
        public string TezBaslikTr { get; set; }
        public string TezBaslikEn { get; set; }
        public string TezOzet { get; set; }
        public string TezOzetHtml { get; set; }
        public string TezAbstract { get; set; }
        public string TezAbstractHtml { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual SRTalepleri SRTalepleri { get; set; }
    }
}
