//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRTalepTipleriAktifAylar
    {
        public int SRAktifAylarID { get; set; }
        public int SRTalepTipID { get; set; }
        public int AyID { get; set; }
    
        public virtual Aylar Aylar { get; set; }
        public virtual SRTalepTipleri SRTalepTipleri { get; set; }
    }
}
