//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalepTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalepTipleri()
        {
            this.TalepGelenTaleplers = new HashSet<TalepGelenTalepler>();
            this.TalepSureciTalepTipleris = new HashSet<TalepSureciTalepTipleri>();
        }
    
        public int TalepTipID { get; set; }
        public Nullable<int> BirlikteBasvurulamayacakTalepTipID { get; set; }
        public bool IsBelgeYuklemeVar { get; set; }
        public bool IsTaahhutIsteniyor { get; set; }
        public string TalepTipAdi { get; set; }
        public string TalepTipAciklama { get; set; }
        public string TaahhutAciklamasi { get; set; }
        public bool IsAktif { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepGelenTalepler> TalepGelenTaleplers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepSureciTalepTipleri> TalepSureciTalepTipleris { get; set; }
    }
}
