//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalepGelenTalepBelgeleri
    {
        public int TalepGelenTaleplerBelgeID { get; set; }
        public int TalepGelenTalepID { get; set; }
        public string DosyaAdi { get; set; }
        public string DosyaYolu { get; set; }
        public bool IsDanismanOnayDosyasi { get; set; }
    
        public virtual TalepGelenTalepler TalepGelenTalepler { get; set; }
    }
}
