//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalepDurumlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalepDurumlari()
        {
            this.TalepGelenTaleplers = new HashSet<TalepGelenTalepler>();
        }
    
        public int TalepDurumID { get; set; }
        public string ClassName { get; set; }
        public string Color { get; set; }
        public string TalepDurumAdi { get; set; }
        public bool IsAktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepGelenTalepler> TalepGelenTaleplers { get; set; }
    }
}
