//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalepGelenTalepler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalepGelenTalepler()
        {
            this.TalepGelenTalepBelgeleris = new HashSet<TalepGelenTalepBelgeleri>();
        }
    
        public int TalepGelenTalepID { get; set; }
        public int TalepSurecID { get; set; }
        public int KullaniciID { get; set; }
        public int TalepTipID { get; set; }
        public int TalepDurumID { get; set; }
        public string TalepDurumAciklamasi { get; set; }
        public System.DateTime TalepTarihi { get; set; }
        public string AdSoyad { get; set; }
        public string OgrenciNo { get; set; }
        public Nullable<int> OgrenimTipID { get; set; }
        public Nullable<int> OgrenimTipKod { get; set; }
        public Nullable<bool> IsTezOnerisiYapildi { get; set; }
        public Nullable<System.DateTime> DoktoraTezOneriTarihi { get; set; }
        public string ProgramKod { get; set; }
        public Nullable<bool> IsYtuArGor { get; set; }
        public Nullable<bool> IsDersYukuTamamlandi { get; set; }
        public Nullable<bool> IsHarcBorcuVar { get; set; }
        public Nullable<int> TalepArGorStatuID { get; set; }
        public Nullable<bool> IsTaahut { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual TalepDurumlari TalepDurumlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepGelenTalepBelgeleri> TalepGelenTalepBelgeleris { get; set; }
        public virtual TalepSurecleri TalepSurecleri { get; set; }
        public virtual TalepTipleri TalepTipleri { get; set; }
    }
}
