//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TikBasvuruOneri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TikBasvuruOneri()
        {
            this.TikBasvuruOneriKomites = new HashSet<TikBasvuruOneriKomite>();
        }
    
        public int TikBasvuruOneriID { get; set; }
        public int TikBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string FormKodu { get; set; }
        public bool IsDegisiklik { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public bool IsTezDiliTr { get; set; }
        public string TezBaslikTr { get; set; }
        public string TezBaslikEn { get; set; }
        public Nullable<bool> IsDilTaahhutuOnaylandi { get; set; }
        public Nullable<bool> DanismanOnayladi { get; set; }
        public Nullable<System.DateTime> DanismanOnayTarihi { get; set; }
        public Nullable<bool> EYKYaGonderildi { get; set; }
        public Nullable<int> EYKYaGonderildiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKYaGonderildiIslemTarihi { get; set; }
        public string EYKYaGonderimDurumAciklamasi { get; set; }
        public Nullable<bool> EYKDaOnaylandi { get; set; }
        public Nullable<int> EYKDaOnaylandiIslemYapanID { get; set; }
        public Nullable<System.DateTime> EYKDaOnaylandiOnayTarihi { get; set; }
        public string EYKDaOnaylanmadiDurumAciklamasi { get; set; }
    
        public virtual TikBasvuru TikBasvuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TikBasvuruOneriKomite> TikBasvuruOneriKomites { get; set; }
    }
}
