//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToBasvuruSavunmaKomite
    {
        public int ToBasvuruSavunmaKomiteID { get; set; }
        public int ToBasvuruSavunmaID { get; set; }
        public System.Guid UniqueID { get; set; }
        public bool IsTezDanismani { get; set; }
        public int TikNum { get; set; }
        public string UnvanAdi { get; set; }
        public string AdSoyad { get; set; }
        public string EMail { get; set; }
        public string UniversiteAdi { get; set; }
        public string AnabilimdaliAdi { get; set; }
        public Nullable<bool> IsLinkGonderildi { get; set; }
        public Nullable<System.DateTime> LinkGonderimTarihi { get; set; }
        public Nullable<int> LinkGonderenID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> DegerlendirmeYapanID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeIslemTarihi { get; set; }
        public string DegerlendirmeIslemYapanIP { get; set; }
        public Nullable<bool> IsCalismaRaporuAltAlanUygun { get; set; }
        public Nullable<int> ToBasvuruSavunmaDurumID { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual ToBasvuruSavunma ToBasvuruSavunma { get; set; }
        public virtual ToBasvuruSavunmaDurumlari ToBasvuruSavunmaDurumlari { get; set; }
    }
}
