//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vW_ProgramBasvuruSonucSayisal
    {
        public int BasvuruSurecID { get; set; }
        public int KullaniciTipID { get; set; }
        public bool MulakatSurecineGirecek { get; set; }
        public int OgrenimTipKod { get; set; }
        public string OgrenimTipAdi { get; set; }
        public string AnabilimDaliKod { get; set; }
        public string AnabilimDaliAdi { get; set; }
        public string ProgramKod { get; set; }
        public string ProgramAdi { get; set; }
        public bool Ucretli { get; set; }
        public Nullable<double> Ucret { get; set; }
        public string KullaniciTipAdi { get; set; }
        public Nullable<int> AlanIciKota { get; set; }
        public Nullable<int> AIKayitCount { get; set; }
        public Nullable<int> AIAsilCount { get; set; }
        public Nullable<int> AIYedekCount { get; set; }
        public Nullable<int> AIKazanamayanCount { get; set; }
        public Nullable<int> AlanDisiKota { get; set; }
        public Nullable<int> ADKayitCount { get; set; }
        public Nullable<int> ADAsilCount { get; set; }
        public Nullable<int> ADYedekCount { get; set; }
        public Nullable<int> ADKazanamayanCount { get; set; }
        public Nullable<int> ToplamBasvuru { get; set; }
    }
}
