//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeterlikBasvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YeterlikBasvuru()
        {
            this.YeterlikBasvuruJuriUyeleris = new HashSet<YeterlikBasvuruJuriUyeleri>();
            this.YeterlikBasvuruKomitelers = new HashSet<YeterlikBasvuruKomiteler>();
        }
    
        public int YeterlikBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public int YeterlikSurecID { get; set; }
        public System.DateTime BasvuruTarihi { get; set; }
        public int KullaniciID { get; set; }
        public string OgrenciNo { get; set; }
        public int OgrenimTipID { get; set; }
        public string ProgramKod { get; set; }
        public int OkuduguDonemNo { get; set; }
        public int YsBasToplamKrediKriteri { get; set; }
        public string YsBasEtikNotKriteri { get; set; }
        public string YsBasSeminerNotKriteri { get; set; }
        public int KayitYil { get; set; }
        public int KayitDonemID { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int TezDanismanID { get; set; }
        public Nullable<bool> IsOnaylandi { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public string OnayAciklama { get; set; }
        public Nullable<bool> IsBasarili { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Donemler Donemler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual OgrenimTipleri OgrenimTipleri { get; set; }
        public virtual Programlar Programlar { get; set; }
        public virtual YeterlikSureci YeterlikSureci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikBasvuruJuriUyeleri> YeterlikBasvuruJuriUyeleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeterlikBasvuruKomiteler> YeterlikBasvuruKomitelers { get; set; }
    }
}
