//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeterlikSurecOgrenimTipleri
    {
        public int YeterlikSurecOgrenimTipID { get; set; }
        public int YeterlikSurecID { get; set; }
        public int OgrenimTipID { get; set; }
        public int OgrenimTipKod { get; set; }
        public Nullable<int> YsBasToplamKrediKriteri { get; set; }
        public string YsBasEtikNotKriteri { get; set; }
        public string YsBasSeminerNotKriteri { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public int IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual OgrenimTipleri OgrenimTipleri { get; set; }
        public virtual YeterlikSureci YeterlikSureci { get; set; }
    }
}
