//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisansUstuBasvuruSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeterlikBasvuruJuriUyeleri
    {
        public int YeterlikBasvuruJuriUyeID { get; set; }
        public int YeterlikBasvuruID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string JuriTipAdi { get; set; }
        public string UnvanAdi { get; set; }
        public string AdSoyad { get; set; }
        public string EMail { get; set; }
        public Nullable<int> UniversiteID { get; set; }
        public string UniversiteAdi { get; set; }
        public Nullable<bool> IsAsilOrYedek { get; set; }
        public Nullable<bool> IsLinkGonderildi { get; set; }
        public Nullable<System.DateTime> LinkGonderimTarihi { get; set; }
        public Nullable<int> LinkGonderenID { get; set; }
        public Nullable<bool> IsBasarili { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> DegerlendirmeYapanID { get; set; }
        public Nullable<System.DateTime> DegerlendirmeIslemTarihi { get; set; }
        public string DegerlendirmeIslemYapanIP { get; set; }
        public System.DateTime IslemTarihi { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public string IslemYapanIP { get; set; }
    
        public virtual Universiteler Universiteler { get; set; }
        public virtual YeterlikBasvuru YeterlikBasvuru { get; set; }
    }
}
